### ISSUE TITLE
Hang on bad syntax for methodmap property

### ISSUE THREAD

**Issue by Fyren** [alliedmodders/sourcepawn#1002]
```sourcepawn
methodmap A {
        property int p {
```

Trying to compile the above as far back as 1.10 hangs instead of producing some kind of error about the syntax.  This loop is the culprit:

https://github.com/alliedmodders/sourcepawn/blob/ebe6a5bd120ac7e82a2c37277864e44d94a98828/compiler/parser.cpp#L1967-L1970

**Comment by dvander** [comment]
Thanks, this has been fixed on master. I think it was also generating infinite error messages. Any kind of while loop in parser.cpp is susceptible to hangs if freading() checks aren't there.
