### ISSUE TITLE
Crash when playing around with methods as "virtuals"

### ISSUE THREAD

**Issue by fakuivan** [alliedmodders/sourcepawn#121]
I was screwing around with methodmaps as menu handlers and the sp compiler crashed when I moved the declaration of ``CTestMenu`` from line 28 to the bottom of the file. There are a lot of weird errors and warnings in there too, I hope this sample can help you discover more of the inconsistencies I encountered when working with methodmaps. I'll attach the source and the dmp file generated by vs. 

[dump.zip](https://github.com/alliedmodders/sourcepawn/files/1066170/dump.zip)
[source.zip](https://github.com/alliedmodders/sourcepawn/files/1066171/source.zip)

**Comment by Fyren** [comment]
It's unlikely anyone will look very far into a test case like that.  Try to pare it down to the minimal code that will produce the assert.  Particularly, get rid of the macros unless they're somehow required to produce the problem.

There definitely is a compiler bug given that it's asserting, but your code shouldn't work anyway.  At the very least, you can't use a methodmap before declaring it (by moving CTestMenu to the bottom) and you can't use methodmap methods before they're declared, even inside that very methodmap (one of your macro'd functions at the top of CBaseMenu).
