### ISSUE TITLE
sqlite database creation bug

### ISSUE THREAD

**Issue by scorpius2k1** [alliedmodders/sourcepawn#122]
SourceMod Forums Thread: [https://forums.alliedmods.net/showthread.php?p=2529668#post2529668](https://forums.alliedmods.net/showthread.php?p=2529668#post2529668)

I am using the latest SourceMod, Linux Server, Half-Life 2: DM. This is driving me absolutely crazy! I am simply trying to create a database, and it does, but for some reason, if I use a timer, and then call StrEqual...it makes a SECOND empty database with whatever name is in the first field of "StrEqual"

Here is an image from FTP showing the two files being made:
http://imgur.com/GFSrYC2l.png

Compile the code below to reproduce it; the databases can be found here
addons/sourcemod/data/sqlite

```
#include <sourcemod> 

new Handle:g_hDB = INVALID_HANDLE; 

public OnPluginStart() 
{ 
    InitDB(); 
    CreateTimer(3.0, wtf_is_going_on); 
} 

stock Action:wtf_is_going_on(Handle:timer) 
{ 
    if(StrEqual("it_makes_an_empty_database_named_with_whatever_is_here", "")) {} 
} 

stock InitDB() 
{ 
    new String:error[255]; 
    g_hDB = SQLite_UseDatabase("my_database", error, sizeof(error)); 
} 
```

**Comment by KyleSanderson** [comment]
So, this one is a little amazing and makes sense related to other bugs I've seen (if that indeed compiles). If you change your timer callback to public that should fix everything.

**Comment by scorpius2k1** [comment]
Very strange! That definitely fixed the "issue" KyleSanderson, usually something simple. thank you!

**Comment by KyleSanderson** [comment]
@scorpius2k1 While your issue may be fixed, this is (probably!) a compiler bug that we should probably track/fix. Thanks for filing!

**Comment by scorpius2k1** [comment]
No problem at all, thanks for the help & all the great features with SM!

**Comment by dvander** [comment]
Good catch. This is indeed a compiler bug. It's easy to see what's going wrong by comparing the assembly listing diffs: the code to `StrEqual` is missing when `wtf_is_going_on` is a stock. But the call is still there, so it's jumping into who knows where, probably a random address in the code section.

My guess is we're forgetting to call `markusage` on read-but-not-executed stocks. Indeed, that seems to be the case here [1]. That should probably be `uREAD|uCALLBACK`.

[1] https://github.com/alliedmodders/sourcepawn/blob/e8e8e25e37f1d7d1e0b15be723de871855d5bf44/compiler/sc3.cpp#L2356

**Comment by dvander** [comment]
PR #123 for this.
