### ISSUE TITLE
Assert at sc6.cpp:884 -- void assemble_to_buffer(MemoryBuffer*, void*): Assertion `sym->codeaddr > sym->addr()' failed

### ISSUE THREAD

**Issue by Fyren** [alliedmodders/sourcepawn#124]
```
void foo()
{
        bar(baz(1));
}

public main() { }
```
If you make `foo` `public`, the compiler doesn't assert.  If you make the body of `foo` just `baz(1)`, it doesn't assert.  The 1.8 compiler successfully compiles (as it ignores `foo` since it's unused).

**Comment by dvander** [comment]
Fixed by #125
