### ISSUE TITLE
'newdecls required' ignores array variables with missing types

### ISSUE THREAD

**Issue by Timocop** [alliedmodders/sourcepawn#160]
> SourcePawn Compiler 1.9.0.5921

I noticed that you can initalize (array) variables with blank types that wont throw any errors while compiling, even with `newdecls required`.

Example plugin: https://forums.alliedmods.net/showthread.php?t=288689
```SourcePawn
#pragma semicolon 1
#pragma newdecls required

int myInt;    //Valid
myInt2;       //error 147: new-style declarations are required // Valid when newdecls are optional
myInt3[6];    //Valid?!
```

**Comment by Fyren** [comment]
Fixed at some point.  The given test case will error with `error 017: undefined symbol "myInt3"`.
