### ISSUE TITLE
cannot assign null to a non-nullable type (Handle)

### ISSUE THREAD

**Issue by AmiT177** [alliedmodders/sourcepawn#173]
Checking if a handle equals to null gives an assignment error.

```
Handle abc;
if(abc == null)
```

**Comment by Headline** [comment]
It’s non-nullable, that’s it’s intention. You were misled to believe that this is an sm bug.

**Comment by AmiT177** [comment]
I wasn't trying to assign tho.

**Comment by Headline** [comment]
Perhaps the error message could be improved, but the underlying principle is true that checking == null on a non-nullable type makes no sense

**Comment by Fyren** [comment]
Headline is right, however, handles are nullable.  Your example doesn't error.
