### ISSUE TITLE
Compiler define __FILE__

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcepawn#182]
What about a implementing define with name `__FILE__` which contains current included filename?

**Comment by Fyren** [comment]
We'd accept that if you're willing to make another PR, especially since `__LINE__` is pretty useless with multiple files without it.

**Comment by CrazyHackGUT** [comment]
I tried implement this is manually before creating issue.
Perhaps I understood [how to create string constants](https://github.com/alliedmodders/sourcepawn/blob/master/compiler/sc1.cpp#L568), but the method is not perfect. Perhaps I found an [input point](https://github.com/alliedmodders/sourcepawn/blob/master/compiler/sc2.cpp#L262) for reading all the included files.

But something went wrong...
Constantly, I get the `core` in the value of the current file. Even in another included file.
![image](https://i.imgur.com/0kT4O9B.png)

What am I doing wrong?
I create a constant once, and while reading any file, I just update its value.

**Comment by Fyren** [comment]
I took a quick look at `insert_subst`, and I think it makes a copy of the given string (`insert_subst` -> `insert_stringpair` -> `duplicatestring`).  Is there something wrong with `add_constant` with `inpfname`?

**Comment by CrazyHackGUT** [comment]
`inpfname` always equals plugin original source. If i try compile `something.sp`, include in `something.sp` another different file like `something/constants.sp`, insert `__FILE__` in `constants.sp`, I whatever receive `something.sp`, but i need `something/constants.sp`.

**Comment by dvander** [comment]
What does the patch look like?

**Comment by CrazyHackGUT** [comment]
I'll post him when I came home.

**Comment by Fyren** [comment]
> `inpfname` always equals plugin original source.

I don't think that's true.  `plungequalifiedfile` pushes `inpfname` to a stack, sets it to the new file, and `readline` pops it back out at EOF.

**Comment by Fyren** [comment]
Implemented via #585.
