### ISSUE TITLE
SPComp 1.10 compiles plugin anyway if include not exists

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcepawn#214]
![default](https://user-images.githubusercontent.com/12576822/40578600-91d8738c-6127-11e8-8f48-0be672c0c16c.png)
I think, lines with Code size, Data size, Stack/heap size, Total requirements don't should outputs to `stdout`, if include don't exists.

**Comment by Headline** [comment]
I think this is a duplicate of #171 and was fixed by https://github.com/alliedmodders/sourcepawn/commit/30f949e81e611f1b8053c423a679a0c32b84e1a3

**Comment by Fyren** [comment]
This is probably a different path resulting in the same problem.
