### ISSUE TITLE
Support for sizeof in function arguments

### ISSUE THREAD

**Issue by Mistrick** [alliedmodders/sourcepawn#226]
Original pawn supports this code.
```
public main()
{
	new a[5];
	test(a);
	new b[10];
	test(b);
}
test(a[], size = sizeof(a))
{
	printf("arr size %d\n", size);
}
```
Output
```
arr size 5
arr size 10
```
Would be great see this in sourcepawn.

**Comment by asherkin** [comment]
This was intentionally removed from SourcePawn in 1.7 due to lack of use and confusion with native binding.
