### ISSUE TITLE
Calling stock functions in global scope returns a terrible compiler error.

### ISSUE THREAD

**Issue by Drifter321** [alliedmodders/sourcepawn#232]
This is from the forums (also discussed in IRC)

When compiling 
`int test = ByteCountToCells(PLATFORM_MAX_PATH)`

in the global scope you get this error
`plugin.sp(3) : fatal error 195: compiler bug: calling stock "ByteCountToCells" that has no generated code`

However, when calling a native instead 
`int test = GetMaxClients()`

you get this

`plugin.sp(3) : error 010: invalid function or declaration
plugin.sp(3 -- 4) : error 008: must be a constant expression; assumed zero
`

As Fyren pointed out the error should probably be what the last one error'd with.

**Comment by Fyren** [comment]
At some point in the last year, this was fixed.  Using current master, both the stock and native used in a global declaration give error 10.
