### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcepawn#233]
https://github.com/alliedmodders/sourcepawn/blob/d653700024004082b2787b2d95e66eba7d2f598e/include/smx/smx-v1-opcodes.h#L129
Here must be `jless` not `jsless` or i wrong?

**Comment by Fyren** [comment]
I think so, but it appears that the text side is only used for `SourcePawn::SpewOpcode` and `jless` won't actually be generated by the compiler (or the optimizer).

**Comment by dvander** [comment]
Yup, typo - feel free to submit a PR.

**Comment by Fyren** [comment]
Thanks.
