### ISSUE TITLE
Switch statements default case not registered as guaranteed return

### ISSUE THREAD

**Issue by Headline** [alliedmodders/sourcepawn#236]
Seems like the default case on switches aren't seen by the compiler as a definite return, and gives us a warning. See testcase below

```c
int main() {
	funct(2);
}
int funct(int input) {
	switch (input) {
		case 0:
			return 1;
		case 1:
			return 2;
		default:
			return 3;
	}
} // warning 209: function "funct" should return a value
```

**Comment by KyleSanderson** [comment]
Doesn't gcc render the same? I swear I've seen this same pattern with a multitude of compilers and it's (slightly) expected. I'd definitely label this as an enhancement though as we've already taken a strong stance on how switch works (prior to Go; I guess).

**Comment by Headline** [comment]
oh; it very well might. I'll check, if so I'll close this

**Comment by Headline** [comment]
Looks like gcc & clang doesn't warn, I'll keep this up

**Comment by assyrianic** [comment]
@Headline C and C++ do not warn about this, both compile as assuming the default will be the return value. It's pointless to have an ending return expression if the default case label also contains a return expression.
