### ISSUE TITLE
Refactor variable reference pre incriment

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcepawn#278]
Now pre incriment of variable reference give code like this:
```
public void MyFunc(int &a)
{
	++a;
}
```
```
push.pri
lref.s.pri 12
inc.pri
sref.s.pri 12
pop.pri
lref.s.pri 12
```
I think need to improve this.

**Comment by assyrianic** [comment]
what's the difference between that output bytecode and with post-inc?

**Comment by dvander** [comment]
You're right it's less than optimal - but in the context of things to do for spcomp - it's low reward and difficult to fix. To prioritize this we'd want evidence that it is a performance problem, which seems unlikely.

The [prototype v2 compiler](https://github.com/alliedmodders/sourcepawn/blob/master/exp/compiler/smx/smx-compiler.cpp#L1329) has two changes that lead to optimal bytecode generation for these cases. First, it tracks whether PRI and ALT are used, which means no unnecessary pushes/pops. Second, it drops the results of expression statements, which eliminates the final load. Both improvements are feasible in spcomp, but - it'd be a lot of work, and gain seems low compared to other refactorings on my wish list.

**Comment by dvander** [comment]
As assyrianic pointed out, I would expect prefix (or even += 1) to have better behavior.

**Comment by dvander** [comment]
The bar for adding new optimizer rules is pretty high. It has historically been buggy and I'm looking to delete it. Again, need some measure of what the performance cost is.

**Comment by assyrianic** [comment]
so pre-inc looks like:
```asm
push.pri
lref.s.pri 12
inc.pri
sref.s.pri 12
pop.pri
lref.s.pri 12
```
while post-inc looks like:
```asm
lref.s.pri 12
push.pri
lref.s.pri 12
inc.pri
sref.s.pri 12
pop.pri
```
but `+= 1` looks like?
```asm
lref.s.pri 12
add.c 1
sref.s.pri 12
```
couple questions would be to ask why `add.c 1` is not simply `inc.pri` and, most importantly, why the incrementing compiled bytecode isn't similar to `+= 1`.

Is the bytecode output the same for non-reference variables?
