### ISSUE TITLE
Crash when using string as array index.

### ISSUE THREAD

**Issue by Hexer10** [alliedmodders/sourcepawn#285]
Hi,

I know that this code is not meant to be compiled, but I think that it should give a proper error instead of crashing.

My test case:

Broken code:
```sourcepawn
public void OnPluginStart()
{
        int arr[5];
        arr["hello"] = 0;
}
```
### Compiled against sourcemod 1.9 windows 10
```
spcomp.exe spcrash.sp
SourcePawn Compiler 1.9.0.6245
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2017 AlliedModders LLC

spcrash.sp(4) : error 033:
```

### Compiled against sourcemod 1.10 windows10
```
spcomp.exe spcrash.sp
SourcePawn Compiler 1.10.0.6355
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

```
### Compiled against sourcemod 1.9 Linux(CentOS 7.2)
```
spcomp spcrash.sp
SourcePawn Compiler 1.9.0.6261
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2017 AlliedModders LLC

Segmentation fault
```

### Compiled against sourcemod 1.10 Linux(CentOS 7.2)
```
spcomp spcrash.sp
SourcePawn Compiler 1.10.0.6341
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

Segmentation fault
```

**Comment by asherkin** [comment]
Spider entertainingly correctly prints the error message for this, probably because it is immune to bad pointers: `plugin.sp(9) : error 033: array must be indexed (variable "")`.

**Comment by Hexer10** [comment]
It still doesn't specify which (array) variable must be indexed.

**Comment by Fyren** [comment]
That's because it's not a variable that needs to be indexed, it's the literal.  That's what the compiler is going to die on before getting to the point of "hey, this is a string being used as an index."

None of the errors surrounding indexing are good.  You can file a separate issue if you want.

**Comment by assyrianic** [comment]
nice -hashmap- crashmap
