### ISSUE TITLE
enum struct compile error indicates different header file

### ISSUE THREAD

**Issue by Starbish** [alliedmodders/sourcepawn#304]
I think it's not a critical error, but report it anyway :)

1. compiler shows that error is from interface.inc, line 8
but it actually exists in 'const.inc', line 15

2. #ifdef preprocessor doesn't seem to work? compiler tells it's unknown directive.
[bugreport_enumstruct.zip](https://github.com/alliedmodders/sourcepawn/files/2718070/bugreport_enumstruct.zip)

**Comment by Fyren** [comment]
Number 2 is not a bug.

**Comment by dvander** [comment]
No. 2 - indeed, I don't think that's a thing.

No. 1 - I can't reproduce it, though I could easily believe it being wrong. What OS did you test on?

**Comment by dvander** [comment]
Whoops - I see it's fixed because Fyren fixed it.
