### ISSUE TITLE
Compiler crash when trying to sum empty bracket scopes

### ISSUE THREAD

**Issue by GAMMACASE** [alliedmodders/sourcepawn#312]
Compiler crashes (1.10.0.6380 also on master) when trying to compile:
```
public void OnPluginStart()
{
	v = () + ()
}
```
crash happens only if there's no semicolon after last empty bracket scope (idk how these are called) and even with ``#pragma semicolon 1``.

**Comment by dvander** [comment]
Thanks for reporting this, should be fixed now.
