### ISSUE TITLE
Argument parsing issue?

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcepawn#313]
I just read and experimented with parsing code for variadic argument, and according to https://github.com/alliedmodders/sourcepawn/blob/master/compiler/parser.cpp#L2786 i was expecting to get error 137 for this case, but isn't.
```
public void foo(int[]& ...)
{
}
```
This give error for float, bool (not test others)
Not give error for int, char.
Is something wrong with analyse algorithm?
Close it, if nothing here.
Tested in latest SM dev compiler and in latest compiler.

**Comment by dvander** [comment]
Thanks, this is now fixed.
