### ISSUE TITLE
Semicolon error points to the wrong file at some case

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcepawn#314]
Minor.
Related to https://github.com/alliedmodders/sourcemod/pull/954.
https://github.com/alliedmodders/sourcemod/blob/master/plugins/include/sourcemod.inc#L722
This case give next error:
```
include\helpers.inc(722) : error 001: expected token: ";", but found "<newline>"
```
My guess:
Parser need to check next token for make sure is it a semicolon, and if next is `#include`, error trace corrupted.

**Comment by dvander** [comment]
Thanks for reporting this, I'm going to merge it to SourceMod shortly since this bug has been causing problems there.
