### ISSUE TITLE
Using undeclared enum struct inside of an array/enum struct gets size wrong.

### ISSUE THREAD

**Issue by GAMMACASE** [alliedmodders/sourcepawn#318]
If you create struct that uses uninitialized struct and if you try to access 4-th or higher element of some array from that uninitialized struct, you will get runtime error.
Here's code example:
```
enum struct test
{
	int id;
	char_t str;
	int len;
}

enum struct char_t
{
	char buff[128];
	int pos;
}

public void OnPluginStart()
{
	test te;
	
	te.str.buff[8] = 's';
}
```
That plugin throws ``[SM] Exception reported: Heap leak detected: hp:2163 should be 2264!`` on startup.
Also I got ``[SM] Exception reported: Invalid memory access`` before, but can't reproduce that again.

Element that may error at runtime will be different if struct has variables going after uninitialized struct variable (In this case in 1st struct ``char_t str``), so in this code example it will be 4 for itself and another 4 for ``int len`` variable, so anything higher 7th element will error at runtime.

Swapping ``test`` and ``char_t`` structs declarations will fix that issue.
I think adding some warning that will inform you that you have uninitialized struct used in another struct will be useful.

**Comment by Fyren** [comment]
This appears to be fixed since early January.  If you want to file issues directly against SP, please test against master, not whatever version SM has pinned.

(You also meant undeclared, not uninitialized.)
