### ISSUE TITLE
Exception reported: Called native with too many parameters (35>32)

### ISSUE THREAD

**Issue by Kaulkwappe** [alliedmodders/sourcepawn#330]
Can you increase SP_MAX_EXEC_PARAMS from 32 to 64 or so?

**Comment by KyleSanderson** [comment]
Can you show a use case? I'm with Janik, this doesn't sound too hot.

**Comment by Kaulkwappe** [comment]
Yes, for a statistics function :)

**Comment by dvander** [comment]
Ooof. Two possible patterns that are both more maintainable than that:

(1) Create an array of all the integers you want to package. Then, stringize, and join them with "," as a separator.
(2) Create an array of all the integers you want to package, then build up the format string in a loop.

**Comment by Kaulkwappe** [comment]
I'm not so familiar with arrays in SourceMod, but this solutions might not be suitable because the native not only uses integers (%d,%d,%d,%d) but strings (%d,%s,%s,%d) too.

The normal way to format the package query strings is by doing that:

`decl String:buffer[256];

Format(
	buffer,
	sizeof(buffer),
	"%d,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d",

	server_id, player_steam_id, kills, deaths, ...
);

ReplaceString(buffer, sizeof(buffer), ",", QUERY_SEPARATOR);`

That will run fine because with the exception of the Steam-ID only integers are used, so the arguments won't contain a comma and so cannot malform the package. But once you use strings (or data from user-input) you want to create your own formatting, let it better call _escaping_ function.

You can't do that with stocks but with natives, as seen above. So Native_QueuePackage() is more an escaping function, a custom Format(). But natives have a big disadvantage when used for such things: They cannot use more than 32 parameters.

**Comment by Fyren** [comment]
You don't have to build the entire string in one call.  You can write functions (or macros if you really want) that append one particular data item at a time, split by type.

Even if your data types aren't uniform, you can use an enum struct to pack them all in a plain array.  Or, use a hashmap/trie (or even a datapack or arraylist).  If you're doing more than just passing the data around, an enum struct or hash will let you give names to particular items.

**Comment by Kaulkwappe** [comment]
Well, you can do that too but I think it is absolutely legitime to use a native in the way I do. A limit of 32 seems already high but it is not when it comes to things like statistics. For a real mass of arguments (more than 64) I would however agree that another way would be more appropriate.

**Comment by dvander** [comment]
I would prefer we didn't expand the param limit just to allow massive format strings. It's kind of an anti-pattern. It'd be better to look for other language features or APIs to do what you're looking for.

**Comment by asherkin** [comment]
While I agree that this use case is a little flimsy, this does feel like a bug to me - the dynamic calling API should probably be able to handle the full limit that varargs can (128) instead of the lower static call limit (32). Other than the minor memory increase, is there any downside to aligning them anyway?

**Comment by KyleSanderson** [comment]
The reason I'm against this is it's simply too many params... even 32 feels high, with structs this should be like... 8. Maybe that's backwards thinking, but it definitely keeps people out of trouble.

**Comment by Kaulkwappe** [comment]
First, thanks for your answers. I really appreciate that!

@KyleSanderson Why does this keep people out of trouble when lowering the limit or what do you mean by that?

I basically don't think such a low hard coded limit is usually a good thing for a dynamic function where in fact actually the coder defines how this function works. Also SourcePawn is (or was?) a low-level language.

Interesting is what maximum of arguments we have in other languages:

**C++**: max. 256 arguments
**C**: max. 127 arguments
**Java**: max. 255 arguments
**PHP**: No limit
**Python**: No limit (the limit of 255 was removed in Python 3.7)

Regarding the proposal from @Fyren to use structs/enums for my specific use case: My function usually does take only few arguments:

```
decl String:data[] = "%d,%d,%s";
QueuePackage(QUERY_PLAYER_GET_ACCOUNT_INFO, data, ENV_1, ENV_2, unique);
```

When I designed my native I felt it would be kind of an overkill to create structs/enums every time. This solution is and was the most simplest and safest for me, the one with the mass of arguments (35 at the moment) is a exception. To be honest I never used enums or structs so I don't even know if they are changeable during runtime because they have to for my use case.

**Comment by assyrianic** [comment]
@Kaulkwappe SourcePawn is a high(er) level language.

Having a limit of parameters forces programmers to break up their code into functions further, which helps promote good practice and more sound code.

**Comment by dvander** [comment]
+1 to assyrianic

I remained unconvinced that passing 35 fixed-position arguments to a function is a good idea. It's certainly not something I've witnessed before in any language. I agree that arbitrary limitations don't make a ton of sense, and I agree that the limit should be consistent across calling conventions. But the impetus for change is not going to be this use case.

**Comment by Enovale** [comment]
I have a particular use case in [my project](https://github.com/Enovale/of-yadr/blob/master/translations/yadr.info.phrases.txt) that I cannot imagine any of the proposed workarounds being a "better" solution for. I have a discord bot relay that gives full customization to the server owner in the way of what the bot outputs. I set up translation phrases where every parameter is documented and the user can assemble messages with whatever information, if any, they want. This means, where possible, I want to provide all possible information that is available to the local scope at that moment in time, every time. This means in some cases having upwards of 33 format parameters. Any way I slice it, I cannot imagine a way to loop over the translation phrase in a way that wouldn't require having multiple phrases for one single actual usage of the translation, which just doesn't make sense, and would make internationalization more cumbersome. I understand that I *could* make it work without a huge format, but the argument not to raise the limit because it forces developers to make better code, I think, is dis-proven by this use case.

**Comment by dvander** [comment]
would variadic arguments help?

**Comment by Enovale** [comment]
> would variadic arguments help?

Considering the variadic arguments would still have to be put into an eventual method call I don't think that makes a difference.

**Comment by Enovale** [comment]
Not trying to be dismissive, genuinely: I don't see how this is supposed to integrate at all with the translation system that I'm using. I'm struggling to see how this is any better than just replacestring'ing something hardcoded like "{STEAMID}" over and over, which I specifically avoided doing.

**Comment by dvander** [comment]
Supplying more than 32 parameters to a variadic function is something we can easily fix. Adding support for more than 32 fixed arguments to a function is less compelling. So if it's the former you need, let me know.

**Comment by Enovale** [comment]
> Adding support for more than 32 fixed arguments to a function is less compelling. So if it's the former you need, let me know.

Principally I really think the limit should be increased outright. Clinging to a theoretical bad codebase is not good reason to keep a limitation in my opinion.

However technically speaking that solution would be plenty for my use case and would resolve my concerns.

**Comment by dvander** [comment]
If you need that many fixed arguments your code needs to be redesigned.

If you want to increase the variadic limit or add better variadic language support, file a new bug, that can be done.
