### ISSUE TITLE
Enum struct array item assignment copy

### ISSUE THREAD

**Issue by rumblefrog** [alliedmodders/sourcepawn#341]
```c
enum struct Inner {
  int x;
}

enum struct Middle {
  Inner inner;
}

Inner g_iInners[10];

public main()
{    
    Middle m;
    
    m.inner = g_iInners[1]; // This line
}
```

`enum_struct_nested_test.sp(15) : error 006: must be assigned to an array`

`SP Compiler 1.10.0.6425`

I'm fairly sure this is already expected, but I think the error message could be improved upon.

**Comment by Headline** [comment]
Expressed this in IRC, but I think this should be a hidden copy if that's possible @dvander

**Comment by dvander** [comment]
I agree this should work, I just don't know how easy it is to get working. I'll take a look though.

**Comment by dvander** [comment]
This luckily got fixed by fixing some other related bugs, thanks for the report!
