### ISSUE TITLE
Delete of undefined "type" returns weird 115 error

### ISSUE THREAD

**Issue by Bara** [alliedmodders/sourcepawn#354]
Tested with SourcePawn Compiler 6431.

Error:
> error 017: undefined symbol "regex2"
> error 115: cannot use delete, type ::ft:regex2:27972:27972 has no destructor

Test Case:
```cpp
#include <regex>

public void OnPluginStart()
{
    Regex rRegex = new Regex("");
    delete regex2;
}
```

I don't know if this errors should be normal, but looks pretty weird.

**Comment by dvander** [comment]
Thanks for the report - the error will print it as a function now. That's about as good as it can get with the current parser (which assumes all unknown names are functions).
