### ISSUE TITLE
crash after 1.10.0.6434 snapshot

### ISSUE THREAD

**Issue by Electr0** [alliedmodders/sourcepawn#357]
# Help us help you
  - [Y ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [Y ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [Y ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Ubuntu 16.04.5
  * Game/AppID (with version if applicable):  Left 4 dead 2 / 550
  * Current SourceMod version: 1.10
  * Current SourceMod snapshot: 1.10.0.6434, jit-x86 (build 1.10.0.6434)
  * Current Metamod: Source snapshot: 1.11.0-dev+1127
  - [Y ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [Y ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [Y ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
I was previosly on snapshot 1.10.0.6426 and it was stable work without crashes. After update 1.10.0.6434 and recomplile all plugins under 1.10.0.6434  compilier (previosly plugins compliled under 1.10.0.6426)  and.. i am got static crashes https://crash.limetech.org/cxhpw4lxlhle

# Problematic Code (or Steps to Reproduce)
  ```
crash in big function writed for grab prop properties, this use switch with 32 or more cases with some with branches to some larger chechs (weapon names for example). 

i am was try recreate it in test plugin to show static crashes,  but it no crash, because it i put structure of crashing function of my plugin. 

Two examples in attachments: **In example 1** i put crashing structure,  at last case of switch (line 223) i am got crash if i am remove this case no crashes, **in example 2** put version where i am change FormatEx(sGetObjectInfo, maxlength, ""); to sGetObjectInfo[0] = '\0'; and crash also fixed.

[example 1.txt](https://github.com/alliedmodders/sourcemod/files/3542025/example.1.txt)
[example 2.txt](https://github.com/alliedmodders/sourcemod/files/3542024/example.2.txt)

But why before this snapshot all work as clock? I know about  https://github.com/alliedmodders/sourcemod/commit/5868ffd04e23bf4c8a3eadfdef6e73d and may be developers take look for found some exeptions?

  ```
# Logs
Crash: https://crash.limetech.org/cxhpw4lxlhle
Crash 2: https://crash.limetech.org/3cel6jsryyp4
Big thanks.

**Comment by Electr0** [comment]
i am try again and make cut of my crashing function

[ally_crash_test2.txt](https://github.com/alliedmodders/sourcepawn/files/3547395/ally_crash_test2.txt)

**Comment by Electr0** [comment]
for provided crashing example crash links: https://crash.limetech.org/wlabyq6loi52 , https://crash.limetech.org/w2tqitw3qaep, https://crash.limetech.org/hhvfzvrsudb6

it some other but all have 

- linux-gate.so!__kernel_vsyscall + 0x9
- libc-2.23.so!gsignal + 0x39
- libc-2.23.so!abort + 0x157
- libc-2.23.so + 0x6737c
- libc-2.23.so + 0x6d2f7
- libc-2.23.so + 0x70398
- libc-2.23.so!__libc_realloc + 0x10e

**Comment by Electr0** [comment]
hm.. i found what in my example i use FSLAMP_GetInfoMas and if plugin what provide this native loaded in crash, if no = no.

this is code of that native from this plugin:

#define MAX_ALLOWED			32
#define MAX_INDEX			9

int g_iEntities[MAX_ALLOWED][MAX_INDEX];

public APLRes AskPluginLoad2(Handle myself, bool late, char[] error, int err_max)
{
    CreateNative("FSLAMP_GetInfoMas", FSLAMP_GetInfoMas);
}

public int FSLAMP_GetInfoMas(Handle plugin, int numParams) 
{
	return g_iEntities[GetNativeCell(1)][GetNativeCell(2)];
}

**Comment by Electr0** [comment]
[ally_crash_test_issue_357.zip](https://github.com/alliedmodders/sourcepawn/files/3547841/ally_crash_test_issue_357.zip)

**Comment by Fyren** [comment]
I tried reproducing this with the latest 1.10 snapshot.  The code in the zip in the comment before this compiles and loads, but running `sm_crash_test` from the server console doesn't crash.  I don't see how it'd be different through chat as a client.

@Electr0, does this still happen with the latest 1.10?  Does the test case you gave us crash if you run `sm_crash_test` in your server console?
