### ISSUE TITLE
Stock function with recursion not removed if not used

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcepawn#358]
Bug: So, i wrote some lib functions that required using of recursion call. Functions not used but stay to compile (not small functions, make +8k bytes to plugin code).
Tested with 1.9.0.6270, 1.10.0.6435 and latest sourcepawn master branch build.
```
// This function not called anywhere else
stock void MyStock()
{
	MyStock();
}
```

**Comment by dvander** [comment]
Thanks for the report, this was a good catch.
