### ISSUE TITLE
Wrong charmax and ucharmax constants value

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcepawn#359]
I think no one ever tried to use it before. When i compile latest compiler build, i saw warning line:
`compiler\parser.cpp(1152): warning C4146: unary minus operator applied to unsigned type, result still unsigned`
So, i decided to look for the constants value.
```
public void OnPluginStart()
{
	PrintToServer("%i", charmax);
	PrintToServer("%i", ucharmax);
}
```
output
```
254
16777215
```

**Comment by dvander** [comment]
I scanned .sp attachments on the forums and found no use of these, so your hunch looks correct. Let's either (a) remove them, or (b) come up with a definition.

Should "char" mean "ASCII char" (meaning, min=0, max=127) or "8-bit value" (meaning min=-128, max=127, umax=255)?

**Comment by asherkin** [comment]
I'm definitely in favour of removing broken things (and offering less hard-coded in the compiler in general).

**Comment by Headline** [comment]
I’m with a, nuke it
