### ISSUE TITLE
IR and Script builder API?

### ISSUE THREAD

**Issue by assyrianic** [alliedmodders/sourcepawn#365]
I'm not sure if this was done for the v2 compiler (couldn't find it in its source code) but I propose that part of the sourcepawn toolkit possess an IR and/or script builder.

I believe having an IR and script builder API would help make it easier to generate bytecode from a compiler which would make compiler and language changes less of a headache to implement in the future.

The IR builder would be a high-level API that generates an instruction stream and the script builder would utilize said instruction stream, or multiple, given from the IR builder and either go straight to the JIT or be dump to an `.smx` file.

The IR builder would be structured into an `SPContext` class that holds data and functions, which are represented by an `SPFunc` class.

The `SPFunc` class itself would store a vector or graph of `SPBlocks` which would contain a vector or inner graph of IR instructions that would map easily to the SMX instructions and/or to the JIT.

**Comment by dvander** [comment]
This is experimental/compiler (spcomp2), which is not being actively developed.
