### ISSUE TITLE
Compiler crashes if can't write output file

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcepawn#396]
If output directory isn't exists, compiler crashes.

I have some repository where contains something plugin and GitHub Actions workflow.
If i pass incorrect path for plugin binary, compiler crashes:
![изображение](https://user-images.githubusercontent.com/12576822/67484231-ae29e380-f678-11e9-95c4-351436ea5c0a.png)
On screenshot, used SM 1.9, but this error exists in 1.10 and 1.11 too.

https://github.com/CrazyHackGUT/sm-ups/runs/273202110
https://github.com/CrazyHackGUT/sm-ups/runs/273202117

**Comment by dvander** [comment]
Thanks for the report, this is fixed now.
