### ISSUE TITLE
Compiler crashes when rational values used as an array size.

### ISSUE THREAD

**Issue by GAMMACASE** [alliedmodders/sourcepawn#407]
Tested on 1.11.0-6462 and also on 1.7.0-4498, here's code example:
```
int arr[2.0];

public void OnPluginStart()
{
	arr[0] = 1;
}
```
Seems like setting array size to something below 2.0 (like 1.5), results in just an error and no crash. I guess it reads that value as a float one and at some point uses it as integer one, and for some reason does not spit error about stupidly big array size and just crashes due to memory limit. Also worth noting that crash only happens when you try to access some index in array, or it'll compile fine with just a warning about unused variable.

Also here's spcomp window output before it's closes:
![image](https://user-images.githubusercontent.com/31375974/68166097-4f1a7780-ff72-11e9-8d60-981aa598c8c5.png)

**Comment by dvander** [comment]
Thanks, this has been fixed!
