### ISSUE TITLE
invalid method code end

### ISSUE THREAD

**Issue by Bara** [alliedmodders/sourcepawn#411]
Found this more randomly.

Test case:
```sp
#include <sourcemod>

public void OnPluginStart()
{
    bool bTest = true;

    if (bTest)
    {
        PrintToServer("True");
    }
    {
        PrintToServer("False");
    }
}
```

With SM1.10 6453 compiler i get this output:
```
sm plugins load test
True
False
```
With SM1.11 6460 compiler :
```
sm plugins load test
[SM] Plugin test.smx failed to load: Unable to load plugin (invalid method code end).
```

Server runs with SM1.10 6454

**Comment by asherkin** [comment]
Is this dependant on the compiler version you use or only the runtime? (or both?)

**Comment by Bara** [comment]
Compiler, and server should run with latest sm1.10 version.

**Comment by dvander** [comment]
I can't reproduce this - any chance you could run the compiler with the -a option (i.e. spcomp test.sp -a) and send me the .asm output file? Either gist.github.com or dvander@alliedmods.net works.

**Comment by Bara** [comment]
Here's the asm output: https://gist.github.com/Bara/3c036433fa2b2580f34b6fc9c05af745

**Comment by dvander** [comment]
Interesting - could you attach or send me the .smx file as well? The asm looks identical (and well-formed) to what I got at home, so I'm not sure what's going on.

**Comment by Bara** [comment]
Sure, when I'm at home

**Comment by Bara** [comment]
the smx + asm file

[411.zip](https://github.com/alliedmodders/sourcepawn/files/3892242/411.zip)

**Comment by Fyren** [comment]
I think this happened to be fixed at some point.  I can reproduce it with spcomp from the given 1.11 revision, but not the latest.  (That said, I don't see what these changes fixed: https://github.com/alliedmodders/sourcepawn/compare/7e69f7eaf58a05e89912487af646b7121e19d1a4...2acbf1c1648d04111081af13f865f012e7bf1740)

@Bara, does using the latest 1.11 compiler work for you?

**Comment by dvander** [comment]
The only thing I can think of there is the markusage() change which may be skipping a function that was being emitted incorrectly (or tripping up the static analyzer in the VM).

**Comment by Bara** [comment]
@Fyren can confirm it, latest compiler build (6473) works fine.

Server: SM 1.10 6458
Compiler SM 1.10 6458
Works

> sm plugins load invalidcodeend
> True
> False
> [SM] Loaded plugin invalidcodeend.smx successfully.



Server: SM 1.10 6458
Compiler SM 1.11 6473
Works

> sm plugins load invalidcodeend
> True
> False
> [SM] Loaded plugin invalidcodeend.smx successfully.

**Comment by Fyren** [comment]
Thanks for verifying.

**Comment by dvander** [comment]
I want to understand what actually changed here, so keeping this open until I get a chance to investigate.

**Comment by dvander** [comment]
Okay, I see what happened now. This bug never existed in 1.10 because callfunction() would check statSKIP before calling markusage(). I forgot to do this in the new parser, but later fixed the oversight. This was the changeset Fyren bisected to.

Without that fix, functions could be revived and listed in the RTTI, even when no code was generated. I'll mark this as fixed and add an assertion to the RTTI code.
