### ISSUE TITLE
How to rework code to new enum structs?

### ISSUE THREAD

**Issue by wopox1337** [alliedmodders/sourcepawn#415]
```
#include <sourcemod>
enum SomeStruct2_s {
    m_3,
    m_4
} // warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs

int iStruct2[SomeStruct2_s];
public void OnPluginStart()
{
    any var2 = m_3;
    iStruct2[var2]++;
}
```
How to rework for new enum Structs?

i try this code:
```
#include <sourcemod>

enum struct SomeStruct1_s {
    int m_1;
    int m_2;
}

SomeStruct1_s iStruct1;
public void OnPluginStart()
{
    // any var1 = m_1; // error 017: undefined symbol "m_1" ???
    any var1 = 0;
	
    // iStruct1[var1]++; // error 117: enum structs cannot be indexed as arrays
    // iStruct1.var1++;  // error 105: cannot find method or property SomeStruct1_s.var1
	
    // var1 == m_1 ? iStruct1.m_1++ : iStruct1.m_2++; // error 017: undefined symbol "m_1"
    var1 == 0 ? iStruct1.m_1++ : iStruct1.m_2++; // i need to use values from struct (as m_1 & m_2)
}
```

**Comment by asherkin** [comment]
Questions like this are a better fit on the forum: https://forums.alliedmods.net/forumdisplay.php?f=107

Your (uncommented) code appears to be largely correct, although it isn't clear what you want to do with the little context provided - dynamic access to struct fields is not supported, the previous code was not valid either as it lost typing information for field access, it was pure luck that the compiler allowed it.

**Comment by wopox1337** [comment]
@asherkin @dvander maybe SourcePawn have any methods for disable warnings (incode)?

After i update Sourcemod i confused.
![image](https://user-images.githubusercontent.com/18553678/69148492-7ed68d00-0ae5-11ea-94c5-53e3045ceebb.png)

**Comment by dvander** [comment]
The warning is there because in SourceMod 1.11, old-style enum structs will simply not compile at all. If you want to use newer compiler features you have to transition your code.

I'd be happy to help with this on the forums (send me a link to the thread) or on IRC (#sourcemod on irc.gamesurge.net).

**Comment by wopox1337** [comment]
Thank you so much for your help. I understand how I need to rework the code, the amount of code will be similar to refactoring. Unfortunately I don't have time for that :(
