### ISSUE TITLE
Boolen Arrays

### ISSUE THREAD

**Issue by Batfoxkid** [alliedmodders/sourcepawn#416]
```c
bool vars[2];
vars = true;
```
For some reason compiling a bool array and setting to true, unindexed, doesn't receive a compile error.
Any other value causes the standard `error 033: array must be indexed`.
Not sure if this was an oversight.

This was tested on SourceMod 1.9, 1.10, 1.11.

**Comment by dvander** [comment]
Amazing. Easy fix, but amazing this went uncaught for so long.
