### ISSUE TITLE
Tag mismatch warning when comparing inheritance methodmaps

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [alliedmodders/sourcepawn#426]
This compiles without warning in `1.10.0.6458`, but `1.11.0.6473` throws a tag mismatch.
Also worth noting that it seems to effect which way round into comparing variables, as comparing `INVALID_HANDLE` first over `array` compiles fine without warning
```js
public void OnPluginStart()
{
	ArrayList array = new ArrayList();
	
	if (array != INVALID_HANDLE)	// warning 213: tag mismatch
	{
		array.Push(1);
	}
	
	if (INVALID_HANDLE != array)	// no warning
	{
		array.Push(2);
	}
}
```

**Comment by Fyren** [comment]
This actually has the same root issue in the new parser as in #424: 

https://github.com/alliedmodders/sourcepawn/blob/4b2eafae2a9db6e55f369513c588af3f11687e5c/compiler/expressions.cpp#L825-L827

The old parser swaps the operands around when the right side is a constant (like `INVALID_HANDLE`).  `matchtag` only walks up the methodmap chain on the right side, so when the new parser doesn't do this swap, we get a tag mismatch.

**Comment by dvander** [comment]
Thanks, the fix for this is now in SourceMod.
