### ISSUE TITLE
SP 1.11 issue?

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcepawn#432]
I don't know, from what side this issue caused (JIT or compiler).
One of users of my plugin (with SM 1.11.0.6473) caused a strange error:
```
L 12/03/2019 - 05:31:08: [SM] Exception reported: Instruction contained invalid parameter
L 12/03/2019 - 05:31:08: [SM] Blaming: materialadmin.smx
L 12/03/2019 - 05:31:08: [SM] Call stack trace:
L 12/03/2019 - 05:31:08: [SM] [1] Line 460, materialadmin/admin.sp::ReadUsers
L 12/03/2019 - 05:31:08: [SM] [2] Line 42, materialadmin/admin.sp::OnRebuildAdminCache

L 12/03/2019 - 05:31:10: [SM] Exception reported: Instruction contained invalid parameter
L 12/03/2019 - 05:31:10: [SM] Blaming: materialadmin.smx
L 12/03/2019 - 05:31:10: [SM] Call stack trace:
L 12/03/2019 - 05:31:10: [SM] [1] Line 82, materialadmin/database.sp::SQL_Callback_ConnectBd
```
Plugin published on Git, and when i push any changes to repository, Travis downloads latest SourceMod build and builds sourcecode with uploading resulted artifact. In artifact Git Commit Hash includes in version.
I requested plugin version and found [archive with build](https://builds.kruzya.me/SB-MaterialAdmin/NewServer/master_58e5a6c_1.11.tar.gz) and [Travis log](https://travis-ci.org/SB-MaterialAdmin/NewServer/jobs/611416677#L380).
In this situtation looks strange places where SourcePawn reports about "Invalid parameter" for instruction. It is [`for` cycle](https://github.com/SB-MaterialAdmin/NewServer/blob/master/addons/sourcemod/scripting/materialadmin/admin.sp#L460) and [calling the stock](https://github.com/SB-MaterialAdmin/NewServer/blob/master/addons/sourcemod/scripting/materialadmin/database.sp#L82) for printing message in client chat.

This is SourcePawn bug or i'm just shit-scripter? :thinking:

**Comment by dvander** [comment]
Does this reproduce with the latest compiler? 1.11 definitely had a code generation issue that could result in this error.

**Comment by CrazyHackGUT** [comment]
I'll check today.

**Comment by CrazyHackGUT** [comment]
Sorry for late response. Yes, this is reproducable also on last compiler (grabbed from last SM 1.11 build).

**Comment by dvander** [comment]
The original .smx hits a bug in an older compiler. But I can still reproduce a verification error compiling from tip of tree. Investigating now.

**Comment by dvander** [comment]
Thanks for reporting this - it's a great bug. Will have a fix and push it to SourceMod as well shortly.
