### ISSUE TITLE
No tag mismatch warnings from switch cases

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [alliedmodders/sourcepawn#435]
Compiled with `1.10.0.6458` and `1.11.0.6477`, `switch` does not have any checks when comparing different tags (`int`, `float`, `enum`, etc), not throwing any tag mismatch warnings. Unsure if intended or not, but this does not feel right.
```js
enum Foo
{
	Foo1,
	Foo2,
	Foo3
}

enum Bar
{
	Bar1,
	Bar2,
	Bar3
}

public void OnPluginStart()
{
	Foo whatever = Foo2;
	
	switch (whatever)
	{
		case Bar1: whatever = Foo2;
		case 3: whatever = Foo3;
		case 7.4: whatever = Foo1;
	}
}
```

**Comment by Fyren** [comment]
It looks like there's no warning at last as far back as 1.6.3, but this seems like a reasonable feature request.

**Comment by rumblefrog** [comment]
Since the PR was merged, this now can be closed I presume?
