### ISSUE TITLE
[Feature Request] More compile date constants

### ISSUE THREAD

**Issue by TheByKotik** [alliedmodders/sourcepawn#444]
More constants about compile date. Something like:
```
__iYYYY__
__szYYYY__
__iYY__
__szYY__
__iMM__    //    Integer value[1-12] for month.
__szMM__    //    String value["1"-"12"] for month.
__iDD__    //    Integer value[1-31] for day.
__szDD__    //    String value["1"-"31"] for day.
__iUNIXTIME__  //  Unix timestamp of compile date.
```
It's must be useful for versions in PluginInfo, debug outputs and etc.
And it will make possible to format the date as you like.

**Comment by dvander** [comment]
Only "UNIXTIME" will really help you with what I assume you're after: better localization of the compile-time constant. If you want to submit a patch for that constant, I'll take it. But these days I'm not a big fan of baking properties of the host environment into the build, it makes builds non-reproducible.
