### ISSUE TITLE
Error on char array cell assign by value of any type

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcepawn#447]
```sourcepawn
public void OnPluginStart()
{
	char str[4];
	any a = 0;
	str[0] = a; // error 179: cannot assign char[] to any[], storage classes differ
	PrintToServer("%s", str);
}
```
Tested in latest SM's master branch ref to SP [305b59e](https://github.com/alliedmodders/sourcepawn/tree/305b59efbf97875da0ebfd46038fdfe519dbe077) and latest SP's master branch [295d735](https://github.com/alliedmodders/sourcepawn/tree/295d73538371a02c7d7dd92044822c0384174933).
It's ok if a have int or char type, but gives error if any type.

**Comment by dvander** [comment]
If this is a regression, I guess we'll need a carve-out for it.

**Comment by Kailo97** [comment]
Bug does not exist in previous versions of SM or SP's `1.10-dev` branch.
I tried to find commit in master branch since bug exits but unsuccessfully. Probably exists from a while ago. Since July 2019 or earlier.

**Comment by dvander** [comment]
I can reproduce this on 1.10-dev.

**Comment by dvander** [comment]
Once we have better control over type checking in the compiler, I'll be more open to a coercion here. For now it seems like there's no pressing need. You can view_as<> to get around it.
