### ISSUE TITLE
Order of boolean operator evaluation appears to have changed in SM1.11

### ISSUE THREAD

**Issue by clugg** [alliedmodders/sourcepawn#470]
I recently received a [bug report](https://github.com/clugg/sm-json/issues/14) for a library of mine which described the library working as expected when compiling with SM1.10 but failing when compiling with SM1.11 (despite compiling without errors).

As can be seen in the diff of my fix, a couple of my conditionals needed to be wrapped in parentheses in order to be evaluated correctly/the same way they were evaluated in SM1.10 and earlier.

https://github.com/clugg/sm-json/commit/c963f14403642be7a70c9cd2244bbdedd304485d

A more generic example, assuming x, y, and z are initialized booleans:
In SM1.10 and below, `x && y || !x && z` appeared to evaluate `x && y` and `!x && z` first, and then boolean OR the two results. However, in SM1.11 this is no longer the case, and in order for the previously described behavior to occur, they must explicitly be wrapped in parentheses: `(x && y) || (!x && z)`.

**Comment by dvander** [comment]
Thanks for the report. It's quite possible we got the chaining incorrect here in the new parsing code, I'll take a look.
