### ISSUE TITLE
Dynamic arrays not fully reinitialised

### ISSUE THREAD

**Issue by asherkin** [alliedmodders/sourcepawn#479]
When a function containing a dynamic array is called multiple times, the array contents persist across multiple calls.

Test case:
```sourcepawn
#include <shell>

int limit = 3;

public void main()
{
    print("Expected:\n");
    for (int i = limit; i >= 0; --i) {
        Test(i, true);
    }

    print("\nActual:\n");
    for (int i = limit; i >= 0; --i) {
        Test(i, false);
    }
}

void Test(int count, bool clear)
{
    print("'");

    char[][] arr = new char[limit][2];

    if (clear) {
        for (int i = 0; i < limit; ++i) {
            arr[i][0] = '\0';
        }
    }

    for (int i = 0; i < count; ++i) {
        arr[i][0] = 'A' + i;
        arr[i][1] = '\0';
    }

    for (int i = 0; i < limit; ++i) {
        print(arr[i]);
    }

    print("'\n");
}
```

Output:
```
Expected:
'ABC'
'AB'
'A'
''

Actual:
'ABC'
'ABC'
'ABC'
'ABC'
```

Reproduced with spcomp included with SM 1.10.0.6488, SM 1.11.0.6541, and current SourcePawn master (03599e9).

See also: https://forums.alliedmods.net/showthread.php?t=324321

**Comment by asherkin** [comment]
I just tried this with #463 and it looks like that has fixed the bug! But a fix for SM stable would probably be nice if possible.

**Comment by dvander** [comment]
Interesting. I have no idea why this happens, or why that patch would have fixed it. Nothing strikes me from the disassembly so I'll have to dig further.
