### ISSUE TITLE
tag mismatch produce second non related error

### ISSUE THREAD

**Issue by Bara** [alliedmodders/sourcepawn#500]
Example plugin:

```sp
#include <sourcemod>

ConVar g_cTest = false;

public void OnPluginStart()
{
    CreateTimer(1.0, Timer_PublicTest)
    CreateTimer(1.0, Timer_Test)
}

public void OnOnConfigsExexuted()
{
    g_cTest = FindConVar("test_convar");
}

public Action Timer_PublicTest(Handle timer)
{

}

Action Timer_Test(Handle timer)
{

}
```

Output with SM1.11.0.6583:
> errors.sp(3) : error 213: tag mismatch (expected "ConVar", got "bool")
> errors.sp(21) : error 203: symbol is never used: "timer"

Output with SM1.10.0.6490
> errors.sp(3) : error 213: tag mismatch
> errors.sp(13) : error 204: symbol is assigned a value that is never used: "g_cTest"

If I change `ConVar g_cTest = false;` to `ConVar g_cTest = null;` it also "fix" the second error `symbol is never used [...]` on SM1.11.

**Comment by dvander** [comment]
I'm unable to reproduce this on master:

```
errors.sp(3) : error 213: tag mismatch (expected "ConVar", got "bool")
```

If it's still an issue please re-open.
