### ISSUE TITLE
Large array declarations has different behavior

### ISSUE THREAD

**Issue by kice** [alliedmodders/sourcepawn#501]
```
#include <sourcemod>

public void OnPluginStart()
{
    int buf1[4096]; // Totoally A okay
    // int buf2[5120]; // [SM] Exception reported: Not enough space on the stack
    // int buf3[8192]; // [SM] Exception reported: Instruction contained invalid parameter
}
```

```
SourcePawn Compiler 1.11.0.6520
```
```
 SourceMod Version Information:
    SourceMod Version: 1.11.0.6520
    SourcePawn Engine: 1.11.0.6520, jit-x86 (build 1.11.0.6520)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Mar 11 2020 21:26:19
    Built from: https://github.com/alliedmodders/sourcemod/commit/ece44718
    Build ID: 6520:ece44718
    http://www.sourcemod.net/
```

I think for array size larger than stack size, it should report `Not enough space on the stack`. I assume very larger array size breaks the VM bytecode.

**Comment by dvander** [comment]
I think the array rewrite PR fixes this. In the meantime, you can do this at the top of your plugin:

    #pragma dynamic 16384

Which will tell the VM to allocate a much bigger stack for your plugin.

**Comment by kice** [comment]
Also I found that if I could declear the array as a global variable without using `#pragma dynamic`, then it looks like we don't have a limit in gloabl scope.

```
#include <sourcemod>

int buf[10485760];

public void OnPluginStart()
{}
```

Then I have three questions:

1. Is this usage intentional? Or `#pragma dynamic` only effect non-global scope?

2. And in this case, I decleared 40MB array (10485760 int), but the memory usage increased more than 120MB (by Windows TaskMgr commit size of srcds.exe), compare to before loading the plugin. 

3. Beside using ArrayList, do we have a better way to store large amount data out of the box?

**Comment by dvander** [comment]
(1) Global scope is static, so computing the upper memory bound is trivial. Not so for function calls which can be recursive, so the compiler doesn't even try. The array rewrite PR fixes this by adding some heuristics. But to answer your question, #pragma dynamic only affects the memory pre-allocated for function calls.

(2) Two copies of global variables are present in memory. One, we keep a read-only copy of the uncompressed file image. Two, to actually run the plugin, we need to allocate a writable copy of the globals. Ideally we would record only the type of "buf" and leave the runtime to instantiate it. Pawn doesn't have this capability yet, so the whole array gets pre-computed and stored with the binary.

(3) You could distribute a file and parse it in on load. It really depends on what kind of data you have and how you're using it.

**Comment by kice** [comment]
In a word, I would need around 20MB of data in memory all the time.

I would like collect player performace data and do some computing in realtime and store the data interested, possibly the data collection rate is around 1~2kb/s (the data size is increasing during the time and reset after one session). I may need to deal with ~20MB of data in one session.

Btw, how to increase the stack size? I scaned the repo very fast and found the stack size looks like hardcoded. It might come in handy if I could `new` very large array in runtime.

**Comment by dvander** [comment]
That's what #pragma dynamic is for. The name is nonsensical, but it sets the maximum size of the stack. (Note that each plugin gets its own stack.)

**Comment by KyleSanderson** [comment]
@kice dvander is absolutely correct. I additionally want to stress how your historical peers have solved this is global data per plugin.  If you want to store 20MB in the plugin (besides doing the decent-ness and asking why - I think we can absolutely fix that), you're able to. Storing 20MB in a single frame through is not idealistic and is quite likely to block your hz cap so I'd much rather work on a redesign than trying to fix this specific scenario.

**Comment by kice** [comment]
Since I want to allocate the data in runtime, it is clear that I made a typo; I would like to ask if the `heap` size is hardcoded. I will try to think a better way as well (or I should use C++ instead).

**Comment by dvander** [comment]
There is not really a heap in Pawn. Instead the stack grows in two directions (bottom-up and top-down), effectively giving every function two stack frames. If you use a dynamically-sized array, it just goes on the "other" stack. There is no limit to stuff originating from handles (eg AdtArray) because it's coming from C++ and not the language itself.

**Comment by dvander** [comment]
This has been fixed on master.
