### ISSUE TITLE
Create tag enumerations like in old syntax

### ISSUE THREAD

**Issue by wopox1337** [alliedmodders/sourcepawn#504]
```SourcePawn
#include <sourcemod>

methodmap SomeMethod __nullable__ < Handle {
    public SomeMethod() {}
    public int GetNum() {return 0;} 
}

methodmap SomeMethod1 __nullable__ {
    public SomeMethod1() {}
    public int GetNum() {return 1;} 
}

typeset MethodsPack {
    function SomeMethod();
    function SomeMethod1();
}

enum struct SomeStruct_s {
// i need something like {SomeMethod, SomeMethod1}:method
    MethodsPack method;
}

public void OnPluginStart() {
    SomeStruct_s struct0;
    struct0.method = new SomeMethod();
    
    PrintToServer("struct0.method.GetNum():%i",struct0.method.GetNum());
    
    SomeStruct_s struct1;
    struct1.method = new SomeMethod1();
    
    PrintToServer("struct1.method.GetNum():%i",struct1.method.GetNum());
}

```

I getting errors on compilation
```C++
SourcePawn Compiler 1.10
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

plugin.sp(25) : error 100: function prototypes do not match
plugin.sp(27) : error 104: cannot find any methods for typeset
plugin.sp(27) : error 029: invalid expression, assumed zero
plugin.sp(27) : warning 215: expression has no effect
plugin.sp(30) : error 100: function prototypes do not match
plugin.sp(32) : error 104: cannot find any methods for typeset
plugin.sp(32) : error 029: invalid expression, assumed zero
plugin.sp(32) : warning 215: expression has no effect

6 Errors.
```

related to https://github.com/alliedmodders/sourcemod/commit/37638ba6fd1e24416cfcdda01611ba8

**Comment by dvander** [comment]
Thanks for the report... this should work, I'm not sure why it doesn't. I'll investigate soon.

**Comment by wopox1337** [comment]
I tried many usage cases...
1) Methodmaps inheritance.
![image](https://user-images.githubusercontent.com/18553678/87703920-379fb980-c7a4-11ea-8aeb-3da511805898.png)

2) set `any` type.
![image](https://user-images.githubusercontent.com/18553678/87704022-6027b380-c7a4-11ea-8bbe-3d02d6b33e80.png)

**Comment by dvander** [comment]
asherkin corrected me, in fact, typeset only works for functions, not for methodmaps. Also, you should not be using `__nullable__`, that is reserved for Handle.

You're effectively asking for one of two things here: discriminated unions, or virtual functions. Obviously... I'd like to have both. But it's a significant amount of work. The big upcoming array refactoring is necessary for either one, and I'm hoping I can work through that by the end of summer.

**Comment by wopox1337** [comment]
Thanks for your answer. How can I solve this task on SourcePawn now? I just need to declare union variable type for better use, but I can't cuz Sourcepawn remove support it. (something like `{tag1, tag2}:variable;`)

**Comment by dvander** [comment]
We didn't remove union type support. It never existed. Multi-tags would not have helped you, because what you want is virtual functions (or discriminated unions, which we've never had).

Your best bet is to use view_as<> to cast to the type you want.

**Comment by wopox1337** [comment]
Yes, this works fine.
![image](https://user-images.githubusercontent.com/18553678/87838927-52a42380-c8a1-11ea-8326-cfd9a9e94396.png)
