### ISSUE TITLE
Multi charactor char definition returning incorrect error code e01 instead of e27.

### ISSUE THREAD

**Issue by c0rp3n** [alliedmodders/sourcepawn#506]
Tried this on the current master and my installed version the error is consistent it seems calling `litchar` in the lexer ~~is skipping to the closing `'` char thus error 27 is not thrown and a semi colon is expected.~~

Compiling:
```c
char g_chr = 'test';
```
Gives this error:
```bash
SourcePawn Compiler 1.11.0.6570
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

.\ok-cat-str-char.sp(1) : error 001: expected token: ";", but found "-identifier-"
.\ok-cat-str-char.sp(1) : warning 203: symbol is never used: "est"
.\ok-cat-str-char.sp(1) : warning 203: symbol is never used: "g_chr"

1 Error.
```

When the expected error code should be:
```
error(27); /* invalid character constant (must be one character) */
```

Edit:
Did a little more digging, it seems that the error is being triggered just it is not being reported to the user as it is overwritten by the missing semi colon error.

**Comment by dvander** [comment]
Thanks, this is fixed on master.
