### ISSUE TITLE
Infinity compiling

### ISSUE THREAD

**Issue by Bara** [alliedmodders/sourcepawn#526]
Found this on latest compiler versions (1.10.0.6497 and 1.11.0.6633).

Example:
```sp
#define TEST TEST

public void OnPluginStart()
{
    PrintToConsoleAll(TEST);
}
```

It compiles until I cancel the process.

And (same 1.11 compiler) with this code it also compiles until I cancel it:
```sp
#define TEST "Test"

public void OnPluginStart()
{
    PrintToConsoleAll(TEST);
}
```

**Comment by Fyren** [comment]
The first example is a bug from upstream (that still exists there).  I can't reproduce any problem with the second.

C and C++ roughly disallow recursive macros, which I guess we can also do.  Or just count replacements and set a limit per line.

**Comment by dvander** [comment]
(Keeping this open to change the way preprocessing replacement works.)

**Comment by dvander** [comment]
Recursive macros are now supported and have the same behavior as C.
