### ISSUE TITLE
No warning/error on left side 1d char arr and right side 2d

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#531]
This code pattern should probably be producing an error upon compilation. Was uncaught in a plugin and caused some issues.

char init is 1d on left but right side is 2d
```sp
public void OnPluginStart() {
    char strings[] = { "string1", "string2", "string3" };
    PrintToServer("%s", strings[1]); // tring1
}
```

**Comment by dvander** [comment]
Good bug. Thanks, this has been fixed on master.
