### ISSUE TITLE
Incorrect syntax parsing?

### ISSUE THREAD

**Issue by TheByKotik** [alliedmodders/sourcepawn#546]
Today i'm worked on simplify very overloaded function through prepocessor's macroses and found *strange* compiling error.
Probable it's my ineptitude in programming but i'm just think to good idea to report this.
```
public void OnPluginStart ()
{
	#define test; str[ i++ ] = '"'; str[ i++ ] = '}';

	char str[16];
	int i;

	if ( i )
	{
		test;	//	Works;
	}
	if ( i ) {
		test;	//	Works;
	}
	if ( i )
	{
		test; }	// Compile error: "error 030: compound statement not closed at the end of file (started at line 5";
}
```
Throwing error on 1.9, 1.10 and 1.11 `spcomp` versions.

**Comment by Fyren** [comment]
More minimal test case:
```
#define test c = '"';
public void main()
{
    char c;
    {
        test; }
}
```

I didn't look into the code yet, but it appears that maybe the `'"'` somehow makes spcomp eat the remainder of the line the replacement happens on.

**Comment by dvander** [comment]
Thanks for the report, this has been fixed.
