### ISSUE TITLE
Access control for methodmap inheritance

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#550]
Requesting feature to control method access (public, private, protected) or some way to prevent exposing certain inherited methods, just as possible in other OOP langs.

**Comment by dvander** [comment]
I'm going to pass on this, and hopefully this justification makes sense:

Methodmaps aren't classes. There is nothing to hide. The "implementation details" are entirely behind natives. If you want a method to not be exported, you can just not export it. `protected` especially has no meaning given that the methodmap extension operator (the `<` symbol) is Handle-based, and Handles do not have inheritance.  You can see in the default include set there are no uses case for the extension operator that would imply meaningful inheritance. (If I've used that word before, that's on me and I'll have to update the docs).

What about enum structs? There, I think, private/protected would make sense. But you can't inherit these yet. When we can implement enum struct inheritance, you can bet private/public will be there.

**Comment by dvander** [comment]
Actually, I'll concede that if you've spun out your own inheritance system based on methodmaps, that does not extend from Handle, there could be an argument for "protected", because you could share an implementation detail with subclasses. But the benefit seems pretty small there.
