### ISSUE TITLE
Travis script borked

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#552]
Travis needs updating for sp repo, similar to recent update for sm repo.

Example output: https://travis-ci.org/github/alliedmodders/sourcepawn/jobs/763875597

**Comment by Bara** [comment]
> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

Moving to github actions would be the better option.

**Comment by dvander** [comment]
I think this is fixed, Peace-Maker has moved us away from Travisty now.
