### ISSUE TITLE
The compiler is sleeping

### ISSUE THREAD

**Issue by wS-SM** [alliedmodders/sourcepawn#554]
The parentheses are incorrect here, but the compiler does not report an error:
`if (kv.GetSectionName(s, sizeof(s) && kv.GotoFirstSubKey()))`

SourceMod Version: 1.10.0.6490

**Comment by asherkin** [comment]
There is no syntax error in your code, what you've written is perfectly valid syntax-wise.

`sizeof(s)` is an `int`, `kv.GotoFirstSubKey()` returns a `bool` - `bool` and `int` can freely coerce between each other, so `int && bool` is a valid comparison to make, and the result of that comparison can be passed in as the `int` 2nd argument to `GetSectionName`.

The fact that isn't what you intended to write is not something the compiler can be expected to check.

**Comment by wS-SM** [comment]
I checked Visual Studio, yes, the compiler considers that there is no error. It turns out this flaw goes much deeper than I thought, because I still think it is wrong. If the function expects a specific type, then there must be an error passing another type. (int && bool) == bool.

**Comment by asherkin** [comment]
SourcePawn's implicit type conversion and promotion rules here are aligned with the behaviour of most other C-like programming languages.
