### ISSUE TITLE
spcomp exits with no output for methodmap static function call

### ISSUE THREAD

**Issue by geominorai** [alliedmodders/sourcepawn#556]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows
  * Current SourceMod version: 1.9.0.6252
  * Current SourceMod snapshot: 1.10.6339
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.

# Description
Compiler exits prematurely with no errors or messages.

# Problematic Code (or Steps to Reproduce)
  ```
methodmap B {
	public static void TestB() {
		A.TestA();
		PrintToServer("TestB");
	}
}

methodmap A {
	public static void TestA() {
		PrintToServer("TestA");
	}
}
  ```

# Logs
Output from Sublime:
```[Finished in 0.9s with exit code 3221225477]```
or
```[Finished in 0.8s]```

Output from spcomp:

**Comment by dvander** [comment]
I can't reproduce this on master - I get an error message instead of a crash or assert. Properly supporting this kind of declaration will be a future thing.
