### ISSUE TITLE
sizeof enum struct returns 0 within 'this' context

### ISSUE THREAD

**Issue by Adrianilloo** [alliedmodders/sourcepawn#559]
I found out that calling `sizeof` for any enum struct within a member function of that enum struct always returns `0`.

```
enum struct STest
{
   int mSample;

    int GetSize()
    {
        return sizeof(STest);
    }
}

public void OnPluginStart()
{
    STest test;
    test.GetSize(); // 0
}
```

SourcePawn Compiler 1.10.0.6502

Is this accepted?

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
