### ISSUE TITLE
1.11 Compiler doesn't throw error 105.

### ISSUE THREAD

**Issue by Natanel-Shitrit** [alliedmodders/sourcepawn#563]
# Problematic code:
```
enum struct A
{
    int a;
}

public void OnPluginStart()
{
    PrintToServer("%d", A::b);
}
```

## 1.10 Compiler: (Correct behavior)
`(8) : error 105: cannot find method or property A.b`

## 1.11 Compiler: (Wrong behavior)
No output at all (probably internal error?)

### Note:
This only relevant to `scope resolution operator (::)` and not `member access (.)`.

**Comment by dragokas** [comment]
You don't have a member named "b" in your code!

**Comment by Natanel-Shitrit** [comment]
> You don't have a member named "b" in your code!

hm, this is the bug - it's not saying 'b' does not exits when using the `scope resolution operator (::)`.

**Comment by dragokas** [comment]
Yeah, sorry, I used the wrong compiler version.
1.11 really not throwing the error at all.

**Comment by dvander** [comment]
Thanks for the report, this has been fixed on master.
