### ISSUE TITLE
Methodmap: Internal Error

### ISSUE THREAD

**Issue by laper32** [alliedmodders/sourcepawn#566]
When using 1.11 to compile my lib: https://github.com/laper32/smlib2/commit/68c749741a121f940bf91b2245ecc4d3629543ee
It shows the error message, and seems it is segment fault.

BTW, on 1.10, it works correctly. A sample is here: https://github.com/laper32/smlib2/commit/94e3884c72d3d9481b406ea33134e8b739e2b83a

I think there is something wrong about the methodmap.

**Comment by JoinedSenses** [comment]
What makes you think it's an issue with the methodmap? To better determine the issue, comment out code until it compiles, then go through and uncomment until you run into the problem.

**Comment by dvander** [comment]
Please attach a reduced test case, otherwise it's difficult for us to investigate this. Please re-open when you get a chance.
