### ISSUE TITLE
Default-initialized enum struct parameter has unexpected values

### ISSUE THREAD

**Issue by Natanel-Shitrit** [alliedmodders/sourcepawn#573]
# Relevant code:
```
enum struct Foo
{
    int i;
    float f;
}

public void OnPluginStart()
{
    TestFunc();
    
    PrintToServer("%f %d", 22.0, 8);
    
    TestFunc();
}

void TestFunc(Foo f = {})
{
    int i = f.i;
    float fl = f.f;
    PrintToServer("%d, %f", i, fl);
}
```

Output:
```
0, 0.000000
22.000000 8
8, 22.000000
```

i ran the code in [spider](https://spider.limetech.io/) but this also bugged out when in a plugin i made compiled with `1.11.0.6516` compiler and server version `1.10.0.6488`.

## Issue name:
~~I don't have a good name for this issue since i don't know what is the name of what's happening here, please rename it if you stumble upon this issue and you know how to call this behavior 😄.~~

**Comment by asherkin** [comment]
I think the quirk here is that `= {}` isn't doing anything at all - in SP that's a partial array init - so you're actually just initialising the first 0 members.

When passed as a param default value it is getting confused about the data it should have vs the data it actually has, which is causing it to over-read the stack memory, see for example the output of:

```sourcepawn
void TestFunc(Foo f = { 45 })
{
    PrintToServer("%d, %f", f.i, f.f);
}
```

The "correct" init (if it was an array, has a warning for enum structs) does work correctly:

```sourcepawn
void TestFunc(Foo f = { 0, ... })
{
    PrintToServer("%d, %f", f.i, f.f);
}
```

It would make sense IMO for SP to treat `{}` the same as `{ 0, ... }` and make the former valid for enum structs and forbid the latter syntax entirely for enum structs (and also include a warning for trying to init less than the "array" length as per the previous example but with an array).

**Comment by dvander** [comment]
agree with everything in asherkin's comment. I'll put this on the todo list.

**Comment by dvander** [comment]
@asherkin any reason not to always zero-fill enum structs, and forbid ellipse syntax entirely?

**Comment by asherkin** [comment]
> @asherkin any reason not to always zero-fill enum structs, and forbid ellipse syntax entirely?

I think that's what I was trying to suggest :D, we already do in variable declarations, it just seems that default parameters are not taking the same path.

**Comment by dvander** [comment]
D'oh, yep, dunno what I was thinking. PR incoming then.

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
