### ISSUE TITLE
Single line buffer initialization does not like macros depending on another macro

### ISSUE THREAD

**Issue by Pheubel** [alliedmodders/sourcepawn#578]
When compiling a plugin with build 6708 of sourcemod 1.11 i noticed that it would raise compile errors related to a macro not being set.
After some puzzling around i managed to shrink the problem area down into the following:

```c
#define MAX_MESSAGE_LENGTH		256
#define MAX_BUFFER_LENGTH		(MAX_MESSAGE_LENGTH * 4)

public void OnPluginStart() {
    char buffer1[MAX_BUFFER_LENGTH], buffer2[MAX_BUFFER_LENGTH];
    LogMessage("buffer1 size: %i buffer2 size: %i", sizeof(buffer1), sizeof(buffer2));
}
```

This piece of code would compile on SM 1.10, but when compiling with 1.11 i get the following errors:
```
addons\sourcemod\scripting\MacroTest.sp(5) : error 017: undefined symbol "MAX_BUFFER_LENGTH"
addons\sourcemod\scripting\MacroTest.sp(5) : error 009: invalid array size (negative, zero or out of bounds)
addons\sourcemod\scripting\MacroTest.sp(5) : error 036: empty statement
addons\sourcemod\scripting\MacroTest.sp(6) : error 017: undefined symbol "buffer2"
```

When toying around i did find some interesting behavior:
* If i were to set `MAX_BUFFER_LENGTH` to `1024`, the equivalent of `(MAX_MESSAGE_LENGTH * 4)`, it would result in a successful compilation.
```c
// this compiles
#define MAX_MESSAGE_LENGTH		256
#define MAX_BUFFER_LENGTH		1024

public void OnPluginStart() {
    char buffer1[MAX_BUFFER_LENGTH], buffer2[MAX_BUFFER_LENGTH];
    LogMessage("buffer1 size: %i buffer2 size: %i", sizeof(buffer1), sizeof(buffer2));
}
```
* If i were to split the initialization of the character buffers over multiple lines, it would result in a successful compilation.
```c
// this compiles
#define MAX_MESSAGE_LENGTH		256
#define MAX_BUFFER_LENGTH		(MAX_MESSAGE_LENGTH * 4)

public void OnPluginStart() {
    char buffer1[MAX_BUFFER_LENGTH];
    char buffer2[MAX_BUFFER_LENGTH];
    LogMessage("buffer1 size: %i buffer2 size: %i", sizeof(buffer1), sizeof(buffer2));
}
```

**Comment by asherkin** [comment]
I've bisected this back to #568, it looks like the intention there was that the restrictions would only apply while parsing a `#define`, but they've actually become global.

**Comment by Fyren** [comment]
This is certainly due to the recent change to disallow recursive macros.  Probably here:

https://github.com/alliedmodders/sourcepawn/blob/ee0c7b5bdab5fc680584af1fceefa4243b284574/compiler/lexer.cpp#L1448

Substitutions go something like this with the caret marking `sequence_end`:
```
char buffer1[MAX_BUFFER_LENGTH], buffer2[MAX_BUFFER_LENGTH];
                             ^
char buffer1[(MAX_MESSAGE_LENGTH * 4)], buffer2[MAX_BUFFER_LENGTH];
                                    ^
char buffer1[(256 * 4)], buffer2[MAX_BUFFER_LENGTH];
                                    ^
```
