### ISSUE TITLE
Server crashes when the SMX plugin doesn't have a function name

### ISSUE THREAD

**Issue by Wend4r** [alliedmodders/sourcepawn#580]
After the changes in #533 , my server crashes when a SMX plugin doesn't have function name.

In line 85, the null `function_name` is dereferenced.
https://github.com/alliedmodders/sourcepawn/blob/07f9c462ab474a7a0a649e40c404de3da5cb32b2/vm/jit.cpp#L83-L85

At a lower level, it looks like this
![image](https://user-images.githubusercontent.com/47463683/124523120-56a4ba80-ddfe-11eb-9898-37788084b7d5.png)
![image](https://user-images.githubusercontent.com/47463683/124523125-5dcbc880-ddfe-11eb-9429-3cc485590d61.png)

**Comment by Fyren** [comment]
What's an example of source that will compile to a plugin that causes this?

**Comment by Wend4r** [comment]
> What's an example of source that will compile to a plugin that causes this?

[example.zip](https://github.com/alliedmodders/sourcepawn/files/6766484/example.zip)
The compiler located in this repository will not be able to compile the code without the function name.

**Comment by Fyren** [comment]
If an unmodified compiler produces a plugin that crashes SM, please reopen this issue.

As I commented in the PR, we don't intend to support stripping out debug info or RTTI.

**Comment by dvander** [comment]
I have improved the validation here to prevent a crash. Unfortunately our test harness doesn't have any way to test prebuilts at the moment. That's something I would like to fix in the future.

Note that RTTI is "optional" in 1.11 in the sense that if it is missing, plugins will still work. This is to allow 1.11 plugins to run on 1.10 and to accelerate the proliferation of enum structs. Once we branch to 1.12, RTTI will start getting embedded into opcodes and will therefore by mandatory.

**Comment by Wend4r** [comment]
The server is still crashing (I'm testing https://github.com/alliedmodders/sourcepawn/commit/91b4bd5a9117e331942f532dbfafa517e0ba1237)

![image](https://user-images.githubusercontent.com/47463683/125135232-53b50d00-e111-11eb-872a-721cd3793cad.png)
![image](https://user-images.githubusercontent.com/47463683/125135398-91b23100-e111-11eb-9c11-2dd98e8a3910.png)

**Comment by Wend4r** [comment]
With https://github.com/alliedmodders/sourcepawn/commit/0ada30fabf97758ce34716670c69786171e41db7 (Before #533 changes) or https://github.com/alliedmodders/sourcepawn/pull/581/commits/03dc8808ba961dfb5793b81561f9e8c038a006ec, the server is working fine

**Comment by dvander** [comment]
If you can attach a .smx test case that reproduces in spshell (eg, we can use it without running srcds), I'll write a patch to fix it and start a new binary test suite.

**Comment by Wend4r** [comment]
> [example.zip](https://github.com/alliedmodders/sourcepawn/files/6766484/example.zip)
> The compiler located in this repository will not be able to compile without the function name.

`example.smx` will be enough to crash the server

**Comment by dvander** [comment]
```
dvander@DESKTOP-GUR1614:~/alliedmodders/sourcepawn$ ./objdir/vm/spshell/linux-x86/spshell /mnt/c/Users/dvander/Desktop/example.smx
dvander@DESKTOP-GUR1614:~/alliedmodders/sourcepawn$
```

If we're to fix test cases not generated by upstream spcomp, they'll need to be reproducible in spshell.

**Comment by Wend4r** [comment]
The problematic code is not in spshell, but in JIT.
https://github.com/alliedmodders/sourcepawn/issues/580#issue-937405243

**Comment by dvander** [comment]
spshell can run with and without the JIT:

```
SourcePawn standalone shell.

Usage: ./shell [-h] file

positional arguments:
  file                      SMX file to execute.

optional arguments:
  -h, --help                Display this help menu.
  -i, --disable-jit         Disable the just-in-time compiler.
  -w, --disable-watchdog    Disable the watchdog timer.
  -p, --jitdump             Enable perf metadata recording for profiling.
  -v, --version             Print version information and exit.
```

**Comment by Wend4r** [comment]
![image](https://user-images.githubusercontent.com/47463683/125143868-bf54a580-e124-11eb-9e16-13ec2fb0ff52.png)
[example_for_shell.zip](https://github.com/alliedmodders/sourcepawn/files/6794263/example_for_shell.zip)

spshell works correctly, but it doesn't use `CompilerBase::emit` how `sourcepawn.jit.x86.so`

**Comment by Wend4r** [comment]
With `"--targets=x86"`, crashes :(

![image](https://user-images.githubusercontent.com/47463683/125145699-f62dba00-e12a-11eb-867a-eecc292fb70b.png)

**Comment by dvander** [comment]
Thanks, I've addressed the issue in this test case.
