### ISSUE TITLE
Using same define twice in another define reports error

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [alliedmodders/sourcepawn#597]
Using different defines in another define compiles fine, but using same define twice in another define reports undefined symbol error.
Compiles fine without error in `1.10.0.6458`, but breaks in `1.11.0.6713`
```
#define FOO 5
#define BAR 7

#define DUCK FOO + BAR
#define QUACK FOO + FOO

public int Apple()
{
	return DUCK;	//no error
}

public int Bread()
{
	return QUACK;	//error 017: undefined symbol "FOO"
}
```

**Comment by dvander** [comment]
Thanks for the great test case - this has been fixed on master and will be backported to 1.11.
