### ISSUE TITLE
Function Literals proposal

### ISSUE THREAD

**Issue by assyrianic** [alliedmodders/sourcepawn#652]
I'd like to make a proposal for there to be function literals, at least to make it easier to create timers.

Here's something to what I have in mind:
Source Code:
```c
CreateTimer(1.0, function Action(Handle hTimer) { return Plugin_Continue; }, _, TIMER_REPEAT|TIMER_FLAG_NO_MAPCHANGE);
```
"Generated" Code:
```c
CreateTimer(1.0, FileNameFunction1, _, TIMER_REPEAT|TIMER_FLAG_NO_MAPCHANGE);

public Action FileNameFunction1(Handle hTimer)
{
    return Plugin_Continue;
}
```

Where each instance of a function literal is then named and that instance is replaced with the given name.

**Comment by dvander** [comment]
This syntax will come eventually, but not soon. We can't implement capturing yet, and without capturing, the value is pretty low.

**Comment by asherkin** [comment]
Related: #181
