### ISSUE TITLE
Failed to load plugin, invalid method code start

### ISSUE THREAD

**Issue by sapphonie** [alliedmodders/sourcepawn#659]
What causes this error? Happening sporadically on compile, not 100% of the time. Sometimes spcomp gives me a working plugin, sometimes it fails to load with invalid method code start. This is on 1.11 mm, latest 1.10 sm.

Plugin (link in sm discord): 

https://cdn.discordapp.com/attachments/335290997317697536/884934872899145768/tf2-comp-fixes.smx

Source:
https://github.com/ldesgoui/tf2-comp-fixes

Opened by asherkin's request.

**Comment by dvander** [comment]
This plugin fails to compile on master:

```
tf2-comp-fixes/scripting/tf2-comp-fixes/projectiles-ignore-teammates.sp(18) : error 021: symbol already defined: "OnEntityCreated"
tf2-comp-fixes/scripting/tf2-comp-fixes/ghostify-soldier-statue.sp(24) : error 021: symbol already defined: "OnEntityCreated"
tf2-comp-fixes/scripting/tf2-comp-fixes/fix-ghost-crossbow-bolts.sp(13) : error 021: symbol already defined: "OnEntityCreated"
```

It looks like it's defining a private function that has the same name as a forward, which is not something we can handle. My guess is: the 1.10 and 1.11 compilers do not see the error, and we get random behavior (including a codegen bug in 1.11).

**Comment by sapphonie** [comment]
![image](https://user-images.githubusercontent.com/15315481/135352509-9d9a8259-fcf5-4075-97d6-fbf1e99497c2.png)
