### ISSUE TITLE
Strange compiler behavior with GetTime() function

### ISSUE THREAD

**Issue by Accelerator74** [alliedmodders/sourcepawn#681]
When testing a new compiler, I found a problem in comparing numbers, namely, when using the time function. I used build 1.11.6798.

```
public void OnPluginStart()
{    
    int time = 1640000000;

    if (GetTime() >= time)
    {
        PrintToServer("Time Error %i >= %i", GetTime(), time);
    }
}
```

Output:
> Time Error 1635337536 >= 1640000000

If you compile the same code on the old compiler and run it on the latest build of the sourcemod, then everything is fine. If you compare the numbers manually, without using the time function, then the error also does not occur. The problem appears only with the `GetTime()` function in the condition.

**Comment by dvander** [comment]
This has been fixed on master.
