### ISSUE TITLE
Enum Struct const array bracket initialization (SourceMod 1.10.0.6522)

### ISSUE THREAD

**Issue by JPZV** [alliedmodders/sourcepawn#687]
I'm having exactly the same error from #412. Same test code, same errors and warning, same issue.

It was supposed to be fixed in the version from that time, but now it seems it's broken again (maybe same reason as before, maybe not).

I tried in both Windows and Linux and in both I get the same errors.

**Comment by Fyren** [comment]
Looks like this was just never put into 1.10, only master.  While I moved it over in SP, SM won't have the change till it updates SP in its repo.
