### ISSUE TITLE
Problem with vectors

### ISSUE THREAD

**Issue by Accelerator74** [alliedmodders/sourcepawn#699]
Noticed the following issue on the compiler 1.11.6805. Most often, the weapon either flies far across the map, or just falls at your feet. The weapon was dropped from the same position of the player in both cases. It looks like the weapon is being thrown to the 0,0,0 coordinates on new compiler.
![20211105135341_1](https://user-images.githubusercontent.com/18032476/140500266-36bc15a6-0871-4cb8-94ed-c1741d98cffd.jpg)

Test code:
```
#include <sdkhooks>
#include <sdktools>

public void OnPluginStart()
{
	RegConsoleCmd("sm_drop", test);
}

public Action test(int client, int args)
{
	int weapon = GetPlayerWeaponSlot(client, 0);
	SDKHooks_DropWeapon(client, weapon);
	return Plugin_Continue;
}
```

**Comment by dvander** [comment]
Thanks, this has been fixed on master.

**Comment by Accelerator74** [comment]
Sometimes this error continues to occur and teleports the object to coordinates 0,0,0. Compiler & sourcemod version 1.11.6833. It is not possible to track exactly how this problem is caused, it manifests itself randomly, but most often at the beginning of the round or at the start of the map.
