### ISSUE TITLE
Empty fields in rtti sections

### ISSUE THREAD

**Issue by peace-maker** [alliedmodders/sourcepawn#700]
The `address` and `codestart` fields of the `.dbg.locals` section are always 0 and all locals are marked as "Arg". There is a similar behavior for the `.dbg.globals` section as well.

https://github.com/alliedmodders/sourcepawn/blob/241b11ccb59710b4bef4cca0b341e95675f85d00/compiler/code-generator.cpp#L224-L244

`AddDebugSymbol` seems to be called too early before all info is set on the symbols.

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
