### ISSUE TITLE
optional string is deprecated?

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcepawn#702]
```
methodmap Met < Handle
{
	public void foo(int a1, char str[] = "")
	{
	}
}
```

sm 1.10.6523 - Compilation OK.
sm 1.11.5805 - Fail with:
```
error 059: function argument may not have a default value (variable "str")
```

**Comment by MAGNAT2645** [comment]
I think that's because you're trying to set a value to the string with fixed size (which is unknown).
Use dynamic string: `char[] str = ""`

**Comment by MAGNAT2645** [comment]
There's a note about array changes (but with different error) for SM 1.11. You should read it:
https://github.com/alliedmodders/sourcepawn/blob/master/docs/upgrading-1.11.md#array-changes

**Comment by dragokas** [comment]
Thanks. Nice article!

More questions.
Why this one doesn't throw error:
```
methodmap Met < Handle
{
	public void foo(int a1, char[] str = "")
	{
	}
}
```
But, this one does:
```
public void foo(int a1, char[] str = "")
{
}
```
```
error 059: function argument may not have a default value (variable "str")
```

**Comment by MAGNAT2645** [comment]
Bug?

**Comment by Fyren** [comment]
Public functions can't have default values for parameters.

**Comment by dragokas** [comment]
Ahh, thanks, I remembered that it worked. So, this one is correct for local using:
```
void foo(int a1, char[] str = "")
{
}
```
