### ISSUE TITLE
The compiler does not see uninitialized variable

### ISSUE THREAD

**Issue by wS-SM** [alliedmodders/sourcepawn#705]
```
public void OnPluginStart()
{
	int i = i;
	PrintToServer("%d", i);
}
```

C++ compiler:
Warning C6001 Using uninitialized memory 'i'.
Error C4700 uninitialized local variable 'i' used.

SourcePawn compiler:
No compilation errors and outputs "2628" to the console.

Because of this, I get "[SM] Exception reported: Invalid Handle 4 (error: 7)":
```
public void MyFn(any data)
{
	// Needed view_as<ArrayList>(data). This is my fault and a flaw in the sm compiler.
	ArrayList ar = view_as<ArrayList>(ar); 
}
```

**Comment by asherkin** [comment]
What compiler version?

**Comment by wS-SM** [comment]
] sm version
 SourceMod Version Information:
    SourceMod Version: 1.10.0.6490
    SourcePawn Engine: 1.10.0.6490, jit-x86 (build 1.10.0.6490)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Jun 21 2020 11:38:32
    Built from: https://github.com/alliedmodders/sourcemod/commit/ac29ac06
    Build ID: 6490:ac29ac06

**Comment by asherkin** [comment]
This is already improved in 1.11 to be a compile error, please make sure to test the development version before opening an issue.

https://github.com/alliedmodders/sourcepawn/blob/master/docs/upgrading-1.11.md#assignment-changes

**Comment by wS-SM** [comment]
Got it, I'm sorry.
