### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by Kenzzer** [alliedmodders/sourcepawn#709]
This a question regarding the terms "(Sourcepawn) 1.12" - "(Sourcepawn) 1.11". 
In this include 
https://github.com/alliedmodders/sourcepawn/blob/18b6d43539b12769078f979dc44ca6ea64e836cc/include/sp_vm_api.h#L587
The feature is announced as having been introduced in Sourcepawn 1.12.

However
https://github.com/alliedmodders/sourcepawn/blob/1d8f052af6e12eacf8b93ce8ec98113f6735e4e0/docs/upgrading-1.11.md#c-changes
Instead indicates this was introduced with Sourcepawn 1.11.

Finally
https://github.com/alliedmodders/sourcepawn/blob/6646bcdd5f0307cac21d6ee5e2e857476adb2729/README.md#sourcepawn-111
The repository README indicates only Sourcepawn 1.11 is being developped, with no indication that Sourcepawn 1.12 has begun development.

Is this a mistake in the header file, or is this some sort of preparation to make Sourcemod/Extensions use this new function before it's actually introduced? I'm assuming it's the former, but I could have missed something hence this issue!

**Comment by asherkin** [comment]
The original SourcePawn 1.11 was dropped and 1.12 was retargeted to 1.11. The include file is outdated - it should say 1.11.

**Comment by dvander** [comment]
Thanks, I've fixed the comment on master.
