### ISSUE TITLE
Compiler problem

### ISSUE THREAD

**Issue by A1mDev** [alliedmodders/sourcepawn#737]
If you compile the plugin mapchooser from the sourcemod using the compiler 1.11.0.6825, then you get the problem with arrays. `PrintToChatAll("item_info[0][VOTEINFO_ITEM_VOTES]: %d", item_info[0][VOTEINFO_ITEM_VOTES]);` - i added debug code like this [here](https://github.com/alliedmodders/sourcemod/blob/master/plugins/mapchooser.sp#L819-L820) between the lines.

Output to chat (sorry for the russian language), pay attention to the percentages.
Old compiler (sourcemod 1.10):
`item_info[0][VOTEINFO_ITEM_VOTES]: 1`
`[SM] Голосование за карту завершено. Следующая карта: 'zoo_swamp_foliage_01'. (За проголосовали 100% из 1 игроков)`
New compiler (sourcemod 1.11.0.6825):
`item_info[0][VOTEINFO_ITEM_VOTES]: 3486264`
`[SM] Голосование за карту завершено. Следующая карта: ''. (За проголосовали 348626400% из 1 игроков)`

**Comment by Headline** [comment]
Can you confirm this issue was fixed boy alliedmodders/sourcemod#1643?

**Comment by A1mDev** [comment]
Yes the problem is solved, though the linux build is still unavailable.
