### ISSUE TITLE
Bad old-syntax dynamic array generation

### ISSUE THREAD

**Issue by A1mDev** [alliedmodders/sourcepawn#742]
The code with which the problem occurred (sourcemod and compiler 1.11.0.6825), it looks like the same problem happens with the new syntax:
```new iNumPlayers;
		decl iPlayers[MaxClients];
		LogError("iPlayers");
		for (new i=1; i<=MaxClients; i++)
		{
			if (!IsClientInGame(i) || IsFakeClient(i) || (GetClientTeam(i) == 1))
			{
				continue;
			}
			LogError("iPlayers[%d]", iNumPlayers);
			iPlayers[iNumPlayers++] = i;
		}
		LogError("iPlayers end");
```
Output of debug messages:
```
L 12/11/2021 - 05:06:29: [match_vote.smx] iPlayers
L 12/11/2021 - 05:06:29: [SM] Exception reported: Invalid memory access
L 12/11/2021 - 05:06:29: [SM] Blaming: match_vote.smx
L 12/11/2021 - 05:06:29: [SM] Call stack trace:
L 12/11/2021 - 05:06:29: [SM]   [1] Line 222, match_vote.sp::StartMatchVote
L 12/11/2021 - 05:06:29: [SM]   [2] Line 177, match_vote.sp::ConfigsMenuHandler
L 12/11/2021 - 05:08:27: [match_vote.smx] iPlayers
L 12/11/2021 - 05:08:27: [match_vote.smx] iPlayers[0]
```

**Comment by A1mDev** [comment]
Very strange behavior, the same code is located below and there are no problems with it.

**Comment by Deathreus** [comment]
You are going beyond the bounds of the array

**Comment by Fyren** [comment]
Minimal test case:
```
public void main() { 
  int i = 4;
  decl arr[i]; //or new
}
```

Generates code like this:
```
push.c 0x4 
break                           
push.pri                        
genarray.z 0x1 ; or genarray.z for new
```

`CheckExprForArrayInitializer` rvals the initializer for a new-syntax dynamic array, but this doesn't get called for old-syntax dynamic arrays.

I can probably fix this tomorrow if dvander doesn't first.

---

> You are going beyond the bounds of the array

While it is true he's going beyond the end of the array, that's not causing the bug he's reporting.

>  it looks like the same problem happens with the new syntax

If you mean by using `new` then yes.  If you mean "newer syntax" as in `int[] arr = new int[i]` then that appears to work currently.

**Comment by Adrianilloo** [comment]
I've apparently stumbled with the same issue (`Invalid memory access` exception) while compatibilizing a plugin to SM 1.11 (UMC), but with a float array:

```
stock bool:GetWeightedRandomSubKey(String:buffer[], size, Handle:weightArr, Handle:nameArr, &index=0)
{
	// ...

	//Convert the adt_array of weights to a normal array.
	new Float:weights[total];
	ConvertAdtArray(weightArr, weights, total);

	// ...
}

//Converts an adt_array to a standard array.
stock ConvertAdtArray(Handle:arr, any:newArr[], size)
{
	new arraySize = GetArraySize(arr);
	new min = size < arraySize ? size : arraySize;

	for (new i = 0; i < min; i++)
	{
		newArr[i] = GetArrayCell(arr, i);
	}
}
```

When I replace the `weights` declaration with `float[] weights = new float[total];` the exception gets fixed. However, I've tried making a test case copy-pasting the minimum amount off base plugin's functions (to originate from `OnPluginStart`) and can't reproduce it. I attach test source below. Why it won't happen here?

Anyway, is it the same issue?
[float_array_arg_error.zip](https://github.com/alliedmodders/sourcepawn/files/7875947/float_array_arg_error.zip)

**Comment by Adrianilloo** [comment]
It should be noted that I've just ran the OP's test case and the exception effectively fixes by e.g. increasing the increasing array's size as in `decl iPlayers[MaxClients + 1];`, while, the concrete internal dynamic array generating denoted issue would completely be affecting the UMC plugin case I commented. Ignoring ASM details, there seems to be something subtle which decides to affect some code and not others (in regards to the exception on non out of bounds array accesses). If anyone would like to reproduce the problem on a proven case (at least failing for me) then [install UMC](https://github.com/Adrianilloo/Ultimate-Mapchooser) and perform some map vote, where exception should arise.

**Comment by Adrianilloo** [comment]
@dvander I recently downloaded latest SM 1.11 dev (with SP 1.11.0.6859) and still have this issue with the UMC plugin. Is this fix supposed to already be present in that SP version?

```
L 02/25/2022 - 23:53:35: [SM] Exception reported: Invalid memory access
L 02/25/2022 - 23:53:35: [SM] Blaming: base/umc-core.smx
L 02/25/2022 - 23:53:35: [SM] Call stack trace:
L 02/25/2022 - 23:53:35: [SM]   [1] Line 620, d:\Source\sourcemod\Ultimate-Mapchooser\addons\sourcemod\scripting\include\umc_utils.inc::ConvertAdtArray
L 02/25/2022 - 23:53:35: [SM]   [2] Line 656, d:\Source\sourcemod\Ultimate-Mapchooser\addons\sourcemod\scripting\include\umc_utils.inc::GetWeightedRandomSubKey
L 02/25/2022 - 23:53:35: [SM]   [3] Line 2697, d:\Source\sourcemod\Ultimate-Mapchooser\addons\sourcemod\scripting\umc-core.sp::GetRandomMap
L 02/25/2022 - 23:53:35: [SM]   [4] Line 2260, d:\Source\sourcemod\Ultimate-Mapchooser\addons\sourcemod\scripting\umc-core.sp::BuildMapVoteItems
L 02/25/2022 - 23:53:35: [SM]   [5] Line 1934, d:\Source\sourcemod\Ultimate-Mapchooser\addons\sourcemod\scripting\umc-core.sp::BuildVoteItems
L 02/25/2022 - 23:53:35: [SM]   [6] Line 1126, d:\Source\sourcemod\Ultimate-Mapchooser\addons\sourcemod\scripting\umc-core.sp::Native_UMCStartVote
L 02/25/2022 - 23:53:35: [SM]   [8] UMC_StartVote
L 02/25/2022 - 23:53:35: [SM]   [9] Line 754, d:\Source\sourcemod\Ultimate-Mapchooser\addons\sourcemod\scripting\umc-rockthevote.sp::StartRTV
L 02/25/2022 - 23:53:35: [SM]   [10] Line 652, d:\Source\sourcemod\Ultimate-Mapchooser\addons\sourcemod\scripting\umc-rockthevote.sp::AttemptRTV
L 02/25/2022 - 23:53:35: [SM]   [11] Line 411, d:\Source\sourcemod\Ultimate-Mapchooser\addons\sourcemod\scripting\umc-rockthevote.sp::OnPlayerChat
```

[Referred script line](https://github.com/Adrianilloo/Ultimate-Mapchooser/blob/master/addons/sourcemod/scripting/include/umc_utils.inc#L620)

Thanks.

**Comment by asherkin** [comment]
No, you need to wait for the SourcePawn update in SourceMod.

**Comment by Adrianilloo** [comment]
Ok, I can confirm my specific issue is solved now too
