### ISSUE TITLE
Support ARM

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcepawn#746]
When we can wait ARM support basically for spcomp?

Apple already started migration own Macintosh devices on own CPU called as `Apple Silicon`, or Apple M1 (if we're talk about current CPU gen) more than year ago.
Also we have too many single-board ARM computer solutions like Raspberry Pi.

**Comment by dvander** [comment]
It should already work fine. If you encounter any specific issues building and running it, please file a bug.
