### ISSUE TITLE
Compiler crashes on "const char[] var" with no initialization

### ISSUE THREAD

**Issue by rtldg** [alliedmodders/sourcepawn#751]
The sourcepawn compiler version I'm using is `1.11.0.6837` from `sourcemod-1.11.0-git6837-windows`

I messed up my OnClientAuthorized callback and ended up with this:
```
public void OnClientAuthorized, const char[] auth)
{
}
```
In an empty file it causes the compiler to process for around half a second and then print
```
//// test.sp
// Internal error.
```
This can be modified a bit like so and it will still happen.
```
int Something, const int asdf[2])
{
}
```

Removing the `const` keyword will allow the compiler to throw errors about expected tokens correctly, so I guess it's `const` specific.

**Comment by Fyren** [comment]
https://github.com/alliedmodders/sourcepawn/commit/990640eb9e4fa9da436b28f005fe77222edaeb30 changed `parse_const` (and also `parse_var`).  With the reported SP code, the statement vector is empty so it dies at the return.  Just changing it to check the length and return nullptr works, but produces ` error 001: expected token: ";", but found "const"`.  Before that change, the error produced was `error 144: void cannot be used as a variable type`.  Do we care which error is reported?

**Comment by Fyren** [comment]
In the case of something like `void func() { const int a[]; ]` instead, the compiler reported `error 001: expected token: "=", but found "["` before the change that causes the bug and the same after the proposed fix.

**Comment by dvander** [comment]
Thanks for the report, this has been fixed in master.
