### ISSUE TITLE
Crash when forward defined twice

### ISSUE THREAD

**Issue by dysphie** [alliedmodders/sourcepawn#762]
By error I declared OnPluginStart twice and it crashed the compiler
```cpp
public void OnPluginStart()
{
}

public void OnPluginStart()
{
}
```

> SourcePawn Compiler 1.11.0.6846
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC
Assertion failed: !target->bound(), file D:\Data\Dev\alliedmodders\sourcemod\sourcepawn\compiler\smx-assembly-buffer.h, line 209

(also tested on 1.11.0.6851)

**Comment by dysphie** [comment]
For what it's worth the full script was https://www.toptal.com/developers/hastebin/meruzasovu.cpp
and it returned

> SourcePawn Compiler 1.11.0.6851
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

> Binary validation failed: Method GetCmdArgInt failed verification: Invalid instruction

> Internal compilation error detected. Please file a bug:
https://github.com/alliedmodders/sourcepawn/issues/new

**Comment by dvander** [comment]
This has been fixed on master, thanks for the report.
