### ISSUE TITLE
Nonexistent default parameter crashes the compiler

### ISSUE THREAD

**Issue by t5mat** [alliedmodders/sourcepawn#771]
# Help us help you
  - [v] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [v] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [v] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Linux
  * Game/AppID (with version if applicable): CS:GO
  * SourceMod version: 1.11.0.6855

# Description

The following code crashes the compiler (nonexistent default parameter):

```sp
float Test(float f = Default)
{
    return f;
}
```

```
/sourcemod/addons/sourcemod/scripting/spcomp64 -v0 -O2 -h -E -o/out/test.smx /src/fastlane/test.sp
Segmentation fault (core dumped)
```

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
