### ISSUE TITLE
SM_PARAM_COPYBACK buffer not explicitly zero'd

### ISSUE THREAD

**Issue by dysphie** [alliedmodders/sourcepawn#772]
When using a SM_PARAM_COPYBACK, if nothing is explicitly written to buffer, the contents will not be zero'd
Problematic code:
```cpp
// plugin.sp:
char garbage[255];

Call_StartForward(fwd);
Call_PushStringEx(garbage, sizeof(garbage), SM_PARAM_STRING_UTF8, SM_PARAM_COPYBACK);
Call_PushCell(sizeof(garbage));
Call_Finish();

PrintToServer(garbage);

// plugin_test.sp:
void MyForward(char[] buffer, int maxlen) 
{
    // nobody here but us chickens
}
```

This prints random memory
From previous discussion:
> asherkin — Today at 5:43 PM
> it looks like without SM_PARAM_STRING_COPY you're just allocated a buffer to store the copyback'd value in, and that doesn't look like it is explicitly zeroed, that appears to be around https://cs.alliedmods.net/sourcemod/source/sourcepawn/vm/scripted-invoker.cpp#228-288

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
