### ISSUE TITLE
.data section optimization

### ISSUE THREAD

**Issue by DeathScore13** [alliedmodders/sourcepawn#779]
translate.google.com:
Please add line ending comparison. For example, 'My string: %s' was once used, but suddenly 'string: %s' was needed, and for a new string, the address from the end of the old string will be taken instead of creating a new one.

Original:
Пожалуйста, добавьте сравнение окончаний строк. К примеру, когда-то была использована 'My  string: %s', но внезапно понадобилось 'string: %s', и для новой строки будет браться адрес из конца старой строки вместо создания новой.

**Comment by asherkin** [comment]
Array literals (including strings) in SourcePawn are mutable, so this isn't a possible optimization - every literal is present in the data section, there is no deduplication as there is no copying.
