### ISSUE TITLE
Defining a const array crashes the compiler

### ISSUE THREAD

**Issue by t5mat** [alliedmodders/sourcepawn#780]
# Help us help you
  - [v] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [v] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [v] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Linux
  * Game/AppID (with version if applicable): CS:GO
  * SourceMod version: 1.11.0.6855

# Description

The following code crashes the compiler:

```sp
public void OnPluginStart()
{
    const float a[3];
}
```

```
/sourcemod/addons/sourcemod/scripting/spcomp64 -v0 -O2 -h -E -o/out/test.smx /src/fastlane/test.sp
Segmentation fault (core dumped)
```

**Comment by dvander** [comment]
```
./test.sp(3) : error 001: expected token: "=", but found "["
./test.sp(3) : error 001: expected token: ";", but found "]"
./test.sp(3) : error 029: invalid expression, assumed zero
```

Seems to get rejected. This syntax didn't work on 1.10 either.

**Comment by Fyren** [comment]
This was a dupe of #751 and already fixed on SP master.

**Comment by t5mat** [comment]
```
SourcePawn Compiler 1.11.0.6857
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC
```

This is the compiler included in 1.11.0.6857 downloaded from https://www.sourcemod.net/downloads.php?branch=dev

Didn't catch that issue, was searching open issues since I figured my version is pretty recent

**Comment by Fyren** [comment]
SM master (usually) doesn't use SP master.  If you look at the SM repo, you can see the SP revision pinned is from three months ago.

**Comment by t5mat** [comment]
Got it, good to know!
