### ISSUE TITLE
Problems with stgopt 

### ISSUE THREAD

**Issue by DeathScore13** [alliedmodders/sourcepawn#783]
For some reason, the stgopt function does not replace opcodes according to the instructions from patterns.h. Everything works fine in 1.10. -O2 is the default.
Example (left 1.11, right 1.10):
![image](https://user-images.githubusercontent.com/73132270/159186772-113593dc-ae5a-4c2b-956c-bda97bfb01d7.png)

**Comment by asherkin** [comment]
The peephole optimiser was removed from spcomp 1.11 a long time ago, the `-O` option is documented as "Deprecated; has no effect". 

If you're finding specific codegen issues please file detailed issues for those, with a description of why it is an issue and source code to reproduce it.
