### ISSUE TITLE
Warning - Variable assigned to itself

### ISSUE THREAD

**Issue by MartLegion** [alliedmodders/sourcepawn#787]
I have noticed this warning while compiling some plugins in SM1.11.
From a coding perspective, it seems valid.

```
public void OnPluginStart()
{
    float noWarning = 2.0;
    noWarning = (noWarning * noWarning);
    
    float warning = 2.0;
    warning *= warning;
}
```

This outputs to:
```
test.sp(7) : warning 226: a variable is assigned to itself (symbol "warning")
```

**Comment by asherkin** [comment]
The naïve fix appears to be that

https://github.com/alliedmodders/sourcepawn/blob/373def0c7bf99604acd79b781aa0a45c5cf388df/compiler/semantics.cpp#L852

 should instead be

```
right_val.ident == iVARIABLE && right_val.sym == left_val.sym && !expr->oper()
```

but I'm not sure if this whole bit actually needs restructuring instead.

**Comment by dvander** [comment]
asherkin's fix looks right. I'll submit a PR shortly.

**Comment by dvander** [comment]
Fixed in master- thanks for the report.
