### ISSUE TITLE
Can't pass `NULL_STRING` to natives with non-const `char[]`

### ISSUE THREAD

**Issue by Adrianilloo** [alliedmodders/sourcepawn#788]
Checked in both SM 1.10 & 1.11.

It seems that passing `NULL_STRING` to a native function with a non-const `char[]` parameter (e.g. `GetLanguageInfo`) causes a compilation error: `error 035: argument type mismatch (argument 2)`.

While doing the same on a custom function compiles fine.

**Comment by JoinedSenses** [comment]
That is a feature, not a bug. You can't use const array variable for non-const parameter. `NULL_STRING` also probably has a different use than what you are using it for.

**Comment by JoinedSenses** [comment]
Example:
```cpp
public void OnPluginStart() {
    f1("String", 7); // error 035: argument type mismatch (argument 1)
}

void f1(const char[] str, int size) {
    f2(str, size);
}

void f2(char[] str, int size) {
    strcopy(str, size, "asdf");
}
```

This is to prevent modifying variables marked as constant.

**Comment by Adrianilloo** [comment]
Yeah, I understand.

I just realized my whole description was based on a side confusion. I had a function with two `const char[]` parameters but switched one of them to be non-const and passed `NULL_STRING` for testing to the `const` one, while I thought I was passing it to the `const` one (lack of attention), leading to that wrong conclusion.
