### ISSUE TITLE
[Feature request] Allow non alphanumeric function names

### ISSUE THREAD

**Issue by sapphonie** [alliedmodders/sourcepawn#792]
Example usecase for derefing a ptr:
```
any *(any ptr)
{
    return view_as<any>( LoadFromAddress( ptr, NumberType_Int32 ) );
}
```

**Comment by JoinedSenses** [comment]
yeah, that's not gonna work.

**Comment by sapphonie** [comment]
Irregardless other languages have support for non alpha functions, i don't see why sourcepawn shouldnt as well

**Comment by JoinedSenses** [comment]
by other languages, you just mean javascript?

**Comment by dvander** [comment]
Stylistically... not a fan.

**Comment by Wend4r** [comment]
I am for the idea of the `Address` methodmap, where would be the `Address.Read()` methods with the entering offset from the base address

**Comment by dvander** [comment]
@Wend4r yes, that's a great idea. Easy PR if anyone takes a shot at it.
