### ISSUE TITLE
Pragmas not affecting includes.

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#797]
Was told that `#pragma semicolon` was intentionally modified to not affect included files. `#pragma newdecls` also now has no effect on included files (so I'm told) and unsure if intentional. If this is intentional, could a compiler switch be added to revert to previous behavior on these? It was a useful behavior to have when updating plugins and maintaining consistency across files. (I'm not even sure why this behavior wouldve been changed)

**Comment by Fyren** [comment]
It is intentional that those pragmas don't affect anything but the file they're in, but you can just use them in each file.  Acting like a global setting as before meant it was extremely annoying if they were used inside a file you included.

We can add a compiler option to default to requiring newdecls like how there is one for semicolons.

**Comment by JoinedSenses** [comment]
Hm. I think it's more annoying to change that behavior since it's mostly known the pragmas can be used after includes.

**Comment by JoinedSenses** [comment]
It would make more sense for the pragmas to be local only for `.inc` files (if for some dumb reason someone puts them in there (which i have never seen)) and be global if it is contained within the main `.sp` file that is being compiled.

**Comment by dvander** [comment]
It doesn't make sense to work that way because third-party includes may not have newdecls. A command-line option to do a global override seems fine though, I'd take a PR for that.

**Comment by JoinedSenses** [comment]
> It doesn't make sense to work that way because third-party includes may not have newdecls. A command-line option to do a global override seems fine though, I'd take a PR for that.

Not sure what you mean. I'm suggesting maintain most previous behavior by giving the plugin dev control over which includes should have the pragma enforced by placing the pragma before or after includes, same as it was before, but if a .inc files has the pragmas, don't set the rules globally, but only locally for just that file.

**Comment by JoinedSenses** [comment]
I've even made a repo for this purpose of maintaining libs by updating syntax to make it easier for people to grab new syntax versions of popular libs. https://github.com/JoinedSenses/SourceMod-IncludeLibrary

**Comment by JoinedSenses** [comment]
> This behavior change makes it annoying to maintain stuff like this, because now I would have to go through every single file to add pragmas.

To add onto this, the new approach is still a problem for backwards compatability because if i add the pragmas to every single file, then that could then fuck up peoples pragmas by modifying global rules for folks using older compilers.

**Comment by dvander** [comment]
That's not a backwards compatibility problem. Updating source to use newer compiler standards means older compilers won't work. This happens all the time.

The old transitive behavior is broken, it doesn't guarantee composition, and it's not coming back. We're moving past the token-paste nature of #includes and you should think of them as being encapsulated translation units.

The command-line override is fine though. I'm in favor of adding lint-style functionality.

**Comment by JoinedSenses** [comment]
Man, I still stand behind this being a terrible solution to the problem.
