### ISSUE TITLE
Global char non array with array initialization not emitting an error

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#802]
Declaring a global and initializing it to a const array does not emit any errors unless another valid declaration exists.

> [7:31 PM] asherkin: your global char arrays are not arrays, and the error is being masked by the invalid use of const
[7:32 PM] asherkin: somehow if every global var is invalid it slips through
[7:33 PM] asherkin: if there is at least one valid one it dies with an assert

```sourcepawn
#include <shell>

// just this = emit no code
const char g_BlockClass = "prop_door_rotating";

// uncomment for assert as well
//int g_MapHeight = 8;


public void main()
{
        print("ok");
}
```

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
