### ISSUE TITLE
Stack error from 2 arrays in separate function

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [alliedmodders/sourcepawn#808]
in SM `1.11.0.6888`, this produces a stack error.
```sourcepawn
public void OnPluginStart()
{
	int array1[4096];
	Duck();
}

void Duck()
{
	int array2[4096];
}
```

If `array1` and `array2` were to be in same function, no error would be made, which makes it look very odd to have error occurred if both arrays were to be in separate function.

There was no error from this from earlier 1.11 until `1.11.0.6796`

**Comment by dvander** [comment]
Whoops. We'll have to make the callstack detection code a little more advanced. Or rather, make it exist again.

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
