### ISSUE TITLE
Preprocessor crashing when missing keyword

### ISSUE THREAD

**Issue by xerox8521** [alliedmodders/sourcepawn#813]
If you check if a constant symbol exists using #if defined FOO and accidently leave out the "defined" part the compiler will crash.

Simple test case:
```sourcepawn
#include <sourcemod>

#define FOO

public void OnPluginStart()
{
	#if FOO
	PrintToServer("Foo");
	#endif
}
```
OS: Windows 10 64 Bit
Compiler Version: 1.11.6888

**Comment by dvander** [comment]
Thanks for the test case, this has been fixed on master.
