### ISSUE TITLE
Segfault when calling ternary-chosen function

### ISSUE THREAD

**Issue by osyu** [alliedmodders/sourcepawn#838]
This segfaults during compilation:

```
public void Func()
{
  bool b;
  (b ? Thing1 : Thing2)();
}

void Thing1() {}
void Thing2() {}
```

Putting this kind of function call in any public functions will cause a crash.

Tested with spcomp 1.12.0.6920 and 1.11.0.6906

**Comment by ProjectSky** [comment]
same issues #837

**Comment by assyrianic** [comment]
IIRC, Function _names_ do not actually point to any block of code, Function variables/names are more _indexes_ into blocks of code. The proper code for the behavior you want is:
```c
Call_StartFunction(null, b? Thing1 : Thing2);
Call_Finish();
```

**Comment by osyu** [comment]
Yeah, I had switched to `b ? Thing1() : Thing2();` instead but still reported this here since compiler crashes are no good

**Comment by dvander** [comment]
This is fixed on master.
