### ISSUE TITLE
All global variables are added to ".pubvars" (sm 1.11)

### ISSUE THREAD

**Issue by schmidt39** [alliedmodders/sourcepawn#843]
Is that intended or a bug?

**Comment by Fyren** [comment]
It is intentionally put in the public table if it's global and assigned or read.

**Comment by schmidt39** [comment]
This means that these methods are equal:

```
int g_Var;
public int g_Var;
```

Sadly.

**Comment by asherkin** [comment]
Why do you want them to be different?

**Comment by schmidt39** [comment]
> Why do you want them to be different?

1. I don't want some plugin or extension to be able to change my variables. If I want them to be able to, then I will declare a variable with "public" tag.

2. I also found another inconvenient moment. If you do SetFailState in the plugin, then after changing the map, SM tries to turn it on again and as a result we have two identical errors in the log (the second one is spam). The logic says: if a plugin has a SetFailState, then you should not try to enable it.

3. And what you are forced to write in each file:

```
#pragma semicolon 1
#pragma newdecls required
```

it's incredibly inconvenient. I had to change the compiler.

**Comment by dvander** [comment]
1. I think you are greatly overestimating this risk. If someone wants to break stuff, they'll find a way, whether the export table contains your variable names or not.
2. This would be a separate bug.
3. No one's forcing you to write that. Unless some kind of law was passed that I'm not aware of.
4. Unloaded plugins have no handle. You're trying to access an invalid value which is a logic error, which should be logged. If you're arguing that unloaded plugins should retain their handle, that's a different (and reasonable) discussion to have - file a separate bug.
