### ISSUE TITLE
Crash when using methodmap property as a method

### ISSUE THREAD

**Issue by dysphie** [alliedmodders/sourcepawn#847]
spcomp version: 1.12.0.6925

code:
```cpp
public void OnPluginStart()
{
	ArrayList arr;
	arr.Length();
}
```

output:

> SourcePawn Compiler 1.12.0.6925
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

**Comment by Fyren** [comment]
Later part of https://github.com/alliedmodders/sourcepawn/issues/750.
