### ISSUE TITLE
No warning/error on function ret not matching typedef/set ret

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#848]
No warning or error is emitted when a function's return type does not match the return type of a typedef/typeset.
Tested on spcomp 1.11.0.6911:
```sourcepawn
typedef MyThing = function void (int i);

int MyThing_f(int i) {
	return i + 1;
}

public void OnPluginStart() {
	f(MyThing_f); // typedef is void but this is int. no warning/error
}

void f(MyThing m) {
	Call_StartFunction(null, m);
	Call_PushCell(1);
	int result;
	Call_Finish(result);

	PrintToServer("%i", result);
}
```

**Comment by dvander** [comment]
This is an explicitly allowed coercion. I don't know why. It was added in SourceMod commit 9ff38bcf80028ddb91db9604732c70a834657f5c in 2014 and the changelog doesn't really explain the reasoning.

**Comment by dvander** [comment]
Fixing this breaks nothing in our official suite, though it breaks almost everything in the SourceMod testsuite. The corpus results, however, are brutal:

```
4668 out of 15196 failed to compile.
```

That's a definite "won't fix", sadly. I think from a type system perspective it's a little weird, but sort of justifiable: the contract is that the return type will be ignored, so it doesn't matter what the callback returns.
