### ISSUE TITLE
operator= broken after 1.10

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#852]
This code compiles/runs as expected for 1.10 but on 1.11+ produces warning 'tag mismatch'

```sourcepawn
stock float operator=(int value) {
    return float(value);
}

public void OnPluginStart() {
    float f = 1; // SM 1.11+: warning 213: tag mismatch (expected "float", got "int")
    PrintToServer("%f", f); // 1.000000
}
```

**Comment by NotnHeavy** [comment]
The same applies for methodmaps: tag mismatch warning, operator overload is not called.

**Comment by dvander** [comment]
Thanks, this has been fixed on master. I didn't have to test this extensively. If you discover bugs with methodmap assignment and operator overloading, please file.
