### ISSUE TITLE
Broken backward compatibility for stack returned arrays

### ISSUE THREAD

**Issue by GAMMACASE** [alliedmodders/sourcepawn#855]
The code in question:
```
public void OnPluginStart()
{
	PrintToServer("String from function: \"%s\"", true ? GetString() : "");
}

char[] GetString()
{
	char buff[8] = "teststr";
	return buff;
}
```

Compiling this code with 1.10 spcomp (1.10.0.6545 and earlier) and running it using latest sm 1.11 (1.11.0.6911) would produce run time error ``Instruction contained invalid parameter``. Error happens exactly when you use ternary in the example above, removing it would work just fine.

Current solution is to recompile the code with 1.11 spcomp, which resolves the issue, although this does mean that plugins compiled with <1.11 spcomps and using such code would not be runnable and produce such errors.

**Comment by dvander** [comment]
Can't reproduce. Please re-open if this still affects the latest build.
