### ISSUE TITLE
Compiler crash when compiling empty Plugin struct declaration

### ISSUE THREAD

**Issue by maxijabase** [alliedmodders/sourcepawn#857]
When attempting to compile the following line, I get a crash:

```cpp
public Plugin myinfo = {}
```

**Crashes with:**
- 1.11-6917 (Windows)
- 1.12-6936 (Windows)

**Does NOT crash with:**
- 1.10-6545 (Windows)

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
