### ISSUE TITLE
Add async await functionality

### ISSUE THREAD

**Issue by ron1232** [alliedmodders/sourcepawn#858]
<h1>Async await:</h1>
<p>An async function is a function declared with the async keyword, and the await keyword is permitted within it. The async and await keywords enable asynchronous, promise-based behavior to be written in a cleaner style, avoiding the need to explicitly configure promise chains.</p>

<p>SourcePawn is a single threaded programming language, the async await functionality works in JavaScript which is also a single threaded language.<p/>
<hr>

- Instead of writing this piece of code (callback hell):

```cpp
void MySQLQuery()
{
    g_Database.Query(SQL_Callback, "SELECT * FROM `table`");
}

void SQL_Callback(Database db, DBResultSet results, const char[] error, any data)
{
    if (results)
    {
        g_Database.Query(SQL_Callback2, "SELECT * FROM `table2`");
    }
}

void SQL_Callback2(Database db, DBResultSet results, const char[] error, any data)
{
    // do whatever with results
}
```

- you would be able to write it without a callback function:

```cpp
async void MySQLQuery()
{
    // await keyword would simply wait for the asynchronous behavior to finish so there is no need for callbacks 👍 
    DBResultSet results = await g_Database.Query("SELECT * FROM `table`");
    
    if (results)
    {
        DBResultSet results2 = await g_Database.Query("SELECT * FROM `table2`");
        
        // do whatever with results
    }
}
```

**Comment by c0rp3n** [comment]
This use case would require #347 so that we avoid a `Database::Query2()` scenario and can overload `Query()` instead without breaking existing code.

Having the addition of unnamed lambdas would also have a similar effect of making the code mire usable see #181 but without requiring overloading and or API changes.

**Comment by rumblefrog** [comment]
While this does look nice, I don't see it happening, at least not anytime soon.

This looks like a feature for higher-level languages like JS, and I don't see it happening in SP, that's based initially on SmallC. I'm not a language designer by any means, but in typed languages, such as Rust & CPP, the Promise type typically is generic over the inner resolved type. And I don't see that happening in SP either.

**Comment by Mooshua** [comment]
I'm no SourcePawn developer, so I don't actually have any knowledge about how the codebase will come into play here. First reaction, I see two "reasonable" implementation paths:

- **Splitting**, where we split functions around `await`ed async functions, and the lower part of the split is moved into it's own callback. Repeat until no more `await`s in a function.
  - *Just problematic*: Awful for debugging, requires an implementation of a callback call-stack. Not fun ☹️ 
- **Blocking**/**Resumable**, where we just steamroll all `async` code into blocking code somehow. Probably would be done by modifying the return pointers of compiler-generated callbacks to point to right after where the `await` code dropped off.
  - *What if we don't await?* Then we're back to the splitting solution above.

These all introduce a plethora of problems:

1. How do we handle `out`-style arguments on non-awaited async functions? Arguments may need to have special treatment in this case, or compiler errors may need to be instated.
2. How do we represent function states, in the event of splitting/blocking? `async` functions will likely receive some opaque callback type from the compiler and will have to do something with it.
3. How will native code react to having dynamic thread types shoved down it's throat?
4. How can we wrap callback native code into async code without having to implement it in native code?
5. What do we do for dynamic dispatches to async functions (if they're somehow possible...)
6. How does the existing simple callback ecosystem react to having an async callback type passed as an argument?
7. We *need* to pass `void` or an equally useless value as a return type to non-awaited async functions, lest we wade into generic territory.

**At this point, you'd be better off writing a compatibility layer for C#/JS/Any language that supports Async/Await.** Seriously. The SourcePawn ecosystem is very old and will likely not react to any of these problems well.

---

## Let's look at an implementation proposal anyways

Anyhow, let's take a look at **splitting**, which I think would be the most popular option. As an example, let's look at a dummy function which just wraps a private function.

```cs
async char[] GetUserNameAsync(int userid)
{
    //  Non-async, blocking code
    User user = GetUserHandle(userid);
    //  Split here! Async code.
    char[] username await GetUserNameFromHandleAsync(user);
    //  Non-async, blocking code, again.
    LogUsername(username);
    return username;
}
```
Under the hood, this **could** be represented this way:

- **Invokes**, where the stack is expanded downwards (just like calling a function!)
- **Wraps**, where the existing slot on the stack is replaced with a new function (just like replacing the return pointer with a free ticket to hell)
- **Returns**, where the stack is moved upwards again (just like `return`ing!)

We have three ways of passing data:
- **Arguments**, which are passed from the current slot down to the below stack slot as arguments
- **Locals**, which are permanently kept at the same stack level until the level is returned,
- **Returns**, which are passed to the same stack level when returned.

In this way, the async system is basically it's own C-like stack system (see: Lua C API). For clarity however, the **sample** code below uses parameters to pass returns and locals.

```cs
/// Compiler-generated
//  This is where the async code begins. This code is executed before the callbacks are invoked.
void GetUserNameAsync__start(Awaiter __callback, int userid)
{
    //  Blocking Code here!
    User user = GetUserHandle(userid);

    //  Now we mark the "continuation" of this function after callback code. 
    //  In other words, this replaces the current function on the callback stack.
    //  As you can see, no one actually likes implementing async code.
    Awaited __next = AwaiterWrap(__callback, GetUserNameAsync__s1);

    //  Create an argument to be placed on the invoked callback when it is invoked.
    AwaiterAppendArg(__next, user);

    //  Record all current locals for the next split in this function (see below)
    AwaiterAppendLocal(__next, userid);
    AwaiterAppendLocal(__next, user);  // Unused but we'll send it anyways.
    AwaiterInvoke(__next, GetUserNameFromHandleAsync__start);
}

//  Okay, now we've entered the callback-split code for GetUsernameFromHandle.
//  Surprise, there's no async code, but we'll just pretend there *is* async code.
//  The argument "user" is populated from AwaiterAppendArg in the parent function.
void GetUserNameFromHandleAsync__start(Awaiter __callback, User user)
{
    //  This *would* be another split in an async function for an async database call.
    //  But for simplicity this is a blocking call.
    char[] name = ExecuteDbQuery(user, GET_NAME);

    AwaiterAppendResult(__callback, name);
    AwaiterReturn(__callback);
}

//  Alright, now we're back in our original function, after doing some tedious async work in `GetUserNameFromHandleAsync`.
//  Because of our call in AwaiterAppendResult, we now have our name as an argument. Yay!
void GetUserNameAsync__s1(Awaiter __callback, int userid, User unused_user, char[] name)
{
    //  Blocking code
    LogUsername(name);

    //  Set the result of GetUserNameAsync!
    AwaiterAppendResult(__callback, name);
    //  Return to whatever poor soul invoked this function.
    AwaiterReturn(__callback);
}
```

As you can see, **living hell on earth** that no self-respecting sourcepawn developer would want to implement. And all for this sorta API:
```cs
async void DoSomeAdminMenuThing(int userid)
{
    char[] name = await GetUserNameAsync(userid);

    LogToChat("Believe it or not, their name is %s!", name);
}
```

## What about wrapping native code?

Honestly I got no clue. What you'd probably want to do is create some sort of dummy function which declares to the programmer how arguments should be passed (see line 1 below)

You could have all "pointer" types be considered "results" to an async function as well as results, such that they are included in the callback parameters for the function above us in the stack.

```cs
//  Create a dummy which is given to programmers.
dummy async SuccessEnum GetUserNameAsync(int userid, char[] name, int length);

//  A hidden implementation used by the compiler.
//  Written by the programmer.
impl async void GetUserNameAsync(Awaiter __callback, int userid, char[] unused_name int length)
{
    //  Pass the callback around native code to avoid changing the callback signature
    AwaiterStore(__callback);
    GetUserNameNative(userid, length, GetUserNameAsync_s1);
}

//  Conforms to the callback type of GetUserNameNative.
void GetUserNameAsync_s1(int userid, char[] name, char[] error)
{
    // Retrieve the burrowed callback
    Awaiter __callback = AwaiterRetrieve();
    
    //  Return parameter (int)
    AwaiterAppendResult(__callback, 0);
    //  Pointer argument parameter (char[])
    AwaiterAppendResult(__callback, name);

    // Done!
    AwaiterReturn(__callback);
}
```

Anyhow, that's my slightly-more-than-two cents.

**Comment by dvander** [comment]
Not going to happen, unfortunately. I objected to this a while ago on conceptual grounds, here: https://github.com/alliedmodders/sourcepawn/issues/661#issuecomment-922110578

But much more problematic is the embedded nature of SourcePawn. Every callback from game to script would have to be audited for whether it's safe to resume at a later point.

**Comment by ron1232** [comment]
> Not going to happen, unfortunately. I objected to this a while ago on conceptual grounds, here: [#661 (comment)](https://github.com/alliedmodders/sourcepawn/issues/661#issuecomment-922110578)
> 
> But much more problematic is the embedded nature of SourcePawn. Every callback from game to script would have to be audited for whether it's safe to resume at a later point.

I'm not a programming language developer but I'm pretty sure that the yield functionality is not the same as the async await.
how does the callback chain work in SourcePawn? isn't there an event loop that waits for every callback to finish?

**Comment by asherkin** [comment]
> how does the callback chain work in SourcePawn? can't there be an event loop that waits for the callback to finish?

You're into SourceMod territory rather than SourcePawn really here, but in essence, not really. The Source engine is inherently blocking and not thread safe, 99% of the API exposed by SourceMod must be executed on the main game thread, and almost all of the forwards exposed by SourceMod are direct hooks on game functions that interrupt execution. There is no central event loop, existing async (threaded) APIs in SourceMod keep track of their own work with any callback functions involved and dispatch results in OnGameFrame generally.

While there are a handful of forwards that could be resumable, they would all need verifying and it would get very confusing from a development standpoint what you could use where. For example, OnPluginStart would be fine (void return, no lifecycle implications), AskPluginLoad2 would be doable (has a return value, but it's interpreted by SM so could be handled in some way to delay loading), OnClientConnect would absolutely not be (it's a hook a function that processes the client connection flow, and needs a return value), and it would be the same for all of the SDKHooks. There are some forwards like OnMapInit or event hooks where some functions can only be called in the context of the callback, which would also not generalise out nicely.

It feels like focusing towards something like #181 first makes sense, it makes some common patterns of code easier to read without massively introducing additional complexity (assuming no scope capture). Then perhaps some experimentation could be done around promises / futures and if they make sense in the context of SourceMod.

**Comment by Mooshua** [comment]
> I'm not a programming language developer but I'm pretty sure that the yield functionality is not the same as the async await.
how does the callback chain work in SourcePawn? can't there be an event loop that waits for the callback to finish?

@ron1232 It has the same effect, which is that the code before and after the yield run at different times, possibly even different ticks, meaning that certain assumptions that sourcemod relies on (such as client indexes) may no longer be valid. That was the concern that was brought up.

**Comment by dvander** [comment]
asherkin's got the right of it. Language level, sure, we could implement it. But it'd effectively be useless and heavily restricted once embedded into SourceMod (and what is SP without SM?)

And lambdas are an easier goal to shoot for...

**Comment by Wend4r** [comment]
In this topic, I need only thread safety from SP so that can execute code in parallel. I believe that from the point of view of the Source engine, necessary to use `IThreadPool` via SourceMod for parallel code execution and sync with the main game thread (aka await).

So parallel execution of the game SP code must pass through SourceMod (natives or something else can be invented), it will be hard to relate to the syntactic part.

**Comment by Mooshua** [comment]
The point is that even if SourcePawn was thread safe, SourceMod (it’s primary consumer) couldn’t have the same thread safety guarantees, so it would likely be disabled.
