### ISSUE TITLE
Compiler crash when assigning a non-struct value to Plugin

### ISSUE THREAD

**Issue by geominorai** [alliedmodders/sourcepawn#860]
Found out from a derp due to mistyping, so the code conceptually does not make sense, but I narrowed down the crash with an example:

```
any aData;
Plugin hPlugin = aData;
```

Tested with `1.11`  compilers and `1.12.0.6946`.  Possibly related to #857.

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
