### ISSUE TITLE
spcomp.exe compiled without icon

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcepawn#867]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 1.11.0.6905
  * Current SourceMod snapshot: 1.11.0.6905
  * Current Metamod: Source snapshot:
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Previously (in SM 1.10) it was very convenient to make association .sp to spcomp.exe having ability to see "Pawn" icon on all .sp files.
Now, icon is missing.

![image](https://user-images.githubusercontent.com/19956568/177635142-497a950f-9965-4cd1-9bde-7ad9415fa51c.png)

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
