### ISSUE TITLE
[Feature Request] unsigned comparison operators

### ISSUE THREAD

**Issue by assyrianic** [alliedmodders/sourcepawn#868]
SP has `>>>` operator for doing unsigned right shifts but has no support for other unsigned operations.

I am proposing comparison operators that treat the operands as unsigned, Either as:
```
+< +> +<= +>=
```
or:
```
<+ >+ <=+ >=+
```
or:
```
<u >u <=u >=u
```

Why?:
From a game POV, there are data/resources that are not intended to be negative (i.e. count of items, using `sizeof`, etc.) but with the current way that comparison ops work, it always requires making sure or asserting that data isn't negative some how.

From an optimization POV:
A comparison operation such as `0 <= i < N` could simply be reduced to `i +< N` or `i <u N` where `i` and `N` are treated as unsigned numbers. Going back to a game POV, this is great for the entity indexes.

From a language POV:
This would remove the need for unsigned integer types as every other operation mirrors the unsigned version except for comparison (and possibly division/modulo?).

**Comment by asherkin** [comment]
Unsigned shift exists because it's required to do that operation (and exists in other languages), adding a bunch of unique syntax for other unsigned operators doesn't seem like a good path forward in any direction. Code is read a lot more than it is written, my preference is definitely towards more verbose and understandable code - SourcePawn's moved past its cryptic syntax phase.

**Comment by dvander** [comment]
For the reasons asherkin stated, I don't think this proposal has any legs.

Unsigned types: not against it. Medium to large size project though.

If you want better assert functionality, that's way easier and smaller in scope. Feel free to propose something and we can see where it goes.

**Comment by assyrianic** [comment]
> For the reasons asherkin stated, I don't think this proposal has any legs.
> 
> Unsigned types: not against it. Medium to large size project though.
> 
> If you want better assert functionality, that's way easier and smaller in scope. Feel free to propose something and we can see where it goes.

another alternative is perhaps natives from SourceMod for an unsigned comparison?
What I have pictured in mind is a single `UnsignedCompare` native with enums to denote whether we're doing an LT, LE, GT, or GE and two arguments:

```c
enum CompareType {
    LT, LE,
    GT, GE,
};
native bool UnsignedCompare(CompareType ct, int a, int b);
```

**Comment by dvander** [comment]
You could implement that without natives. Here's something dumb, that I have completely not tested:

```
stock int CompareUint32(int x, int y) {
    if (x == y) return 0;
    int sign_x = x & 0x80000000;
    int sign_y = y & 0x80000000;
    if (sign_x == sign_y)
        return x < y ? -1 : 1;
    return sign_x ? 1 : -1;
```

**Comment by assyrianic** [comment]
> You could implement that without natives. Here's something dumb, that I have completely not tested:
> 
> ```
> stock int CompareUint32(int x, int y) {
>     if (x == y) return 0;
>     int sign_x = x & 0x80000000;
>     int sign_y = y & 0x80000000;
>     if (sign_x == sign_y)
>         return x < y ? -1 : 1;
>     return sign_x ? 1 : -1;
> }
> ```

This isn't a bad idea but the purpose of this proposal was so that we could enjoy the benefits of what a `uint` type would bring without requiring the additional effort of making a `uint` type.

I mean overall, what would really change with a `uint` type in terms of behavior beyond the comparison operators? The arithmetic, bitwise, and logical operations will function the exact same way they did for the regular `int` (except the `>>` operator).

The only thing left is just the relational operators given that they interpret integer data exclusively as _signed_ . The operators, with understandable criticism from @asherkin , were at least some type of mechanism where integer data can be interpreted as unsigned for whatever data the script dev needs to interpret as never being negative for the purpose of comparison.

Like I said, there are others to possibly implement a mechanism like this without (ugly looking) operators but from my POV, this is a solution that achieves having a way to do unsigned comparison whilst maintaining backwards compatibility and not requiring as much effort as needing to add unsigned types while achieving the remaining practical uses an unsigned type would provide.
