### ISSUE TITLE
Const methods for enum structs 

### ISSUE THREAD

**Issue by inklesspen1rus** [alliedmodders/sourcepawn#875]
Currently there is no way to create const method. So if I have const structure, I have copy it into non-const structure or use functions with const-structure parameter:

```cpp
enum struct MyStruct {
	int x;

	void Init() {

	}

	//bool Check() const { // error
	bool Check() {
		return true;
	}
}

public void test() {
	MyStruct s;
	s.Init();
	test2(s);
}

bool test2(const MyStruct s) {
	//MyStruct s2 = s; // array sizes do not match
	MyStruct s2;
	memcpy(s, s2, sizeof MyStruct);

	//return s.Check(); // argument 0 type mismatch
	return s2.Check();
}

void memcpy(const any[] src, any[] dst, int size) {
	for(int i = 0; i < size; ++i) {
		dst[i] = src[i];
	}
}
```

I think it's a good idea let declare const methods to assume that data will not change after this method execution.

**Comment by dvander** [comment]
You're not gonna like my answer, but: don't bother using const. It has very little value add. It's just clutter.On Apr 25, 2023 10:01 AM, inklesspen_rus ***@***.***> wrote:
Currently it's no way to create const method. So if I have const structure, I have copy it into non-const structure or use functions with const-structure parameter:
enum struct MyStruct {
	int x;

	void Init() {

	}

	//bool Check() const { // error
	bool Check() {
		return true;
	}
}

public void test() {
	MyStruct s;
	s.Init();
	test2(s);
}

bool test2(const MyStruct s) {
	//MyStruct s2 = s; // array sizes do not match
	MyStruct s2;
	memcpy(s, s2, sizeof MyStruct);

	//return s.Check(); // argument 0 type mismatch
	return s2.Check();
}

void memcpy(const any[] src, any[] dst, int size) {
	for(int i = 0; i < size; ++i) {
		dst[i] = src[i];
	}
}
I think it's a good idea let declare const methods to assume that data will not change after this method execution.

**Comment by dvander** [comment]
The only language with this kind of "const" is C++, and while C++ is perfect - nay, immeasurable in its beauty - I don't think it makes sense for a scripting language. My very strong suspicion is that if "const" didn't exist to begin with, no one would really care.
