### ISSUE TITLE
Comparison operators have wrong calculation order in statement condition

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcepawn#876]
Upgrading my SourcePawn decompiler for 1.11 found:
In "If/For/While" condition the second operand calculated in first and the first operand calculated last

Can be reproduced on SourcePawn Compiler 1.11.0.6931
And SourcePawn latest master [4343113](https://github.com/alliedmodders/sourcepawn/commit/43431131ac32eb47548fb6b4b8a099967e50c651)
Not reproduced on SourcePawn Compiler 1.10.0.6545
Not reproduced with `==` or `!=`
Not reproduced in expression context - as param, as assigned value and etc.

Estimate severity - ~critical. Change behavior of code
Definitely regression test required to add

## Test case
```sourcepawn
public void OnPluginStart()
{
	int i = 0;
	// Expected 0 >= 10
	// 1.11 Real 10 >= 10
	if (i >= (i = 10))
	{
		PrintToServer("1: 1");
	}
	else
	{
		PrintToServer("1: 0");
	}
	i = 0;
	PrintToServer("2: %d", i >= (i = 10));
}
```
1.11.0.6931 output:
```
1: 1
2: 0
```

**Comment by asherkin** [comment]
What's the real code that caused this?

**Comment by Kailo97** [comment]
I upgrading my SourcePawn decompiler for 1.11 compiled smx. I made for decompiler test some test examples
```sourcepawn
native void Foo(int a = 1);
public void NormalForLoop()
{
	Foo();
	for (int i = 0; i < 10; i++)
	{
		Foo(i);
	}
	Foo();
}
```
And got bytecode
```
3748: break
3752: push.c 0
3760: const.pri 10 // 3844
3768: push.pri
3772: load.s.pri -4
3780: pop.alt
3784: jsgeq 3852
```
I thought order changed only with const value and decide to try
```sourcepawn
native void Foo(int a = 1);
public void NormalForLoop()
{
	Foo();
	for (int i = 0; i - 5 < 10 + i; i++)
	{
		Foo(i);
	}
	Foo();
}
```
But byte code still execute second operand first
```
3748: break
3752: push.c 0
3760: load.s.pri -4 // 3876
3768: const.alt 10
3776: add
3780: push.pri
3784: load.s.pri -4
3792: push.pri
3796: const.pri 5
3804: pop.alt
3808: sub.alt
3812: pop.alt
3816: jsgeq 3884
```
So, I don't have "the real code" where this bug appears. Can be found in any condition where both operands affected by same environment context. More real example looks like
```sourcepawn
int Foo()
{
	static int i = 1;
	return (i = 1 - i);
}

public void OnPluginStart()
{
	if (Foo() < Foo())
	{
		PrintToServer("1: 1");
	}
	else
	{
		PrintToServer("1: 0");
	}
}
```

**Comment by Kailo97** [comment]
Full bytecode for "test case". PrintToServer is 3636-3736
```
3488: proc
3492: break
3496: heap.save
3500: break
3504: push.c 0
3512: break
3516: const.pri 10
3524: stor.s.pri -4
3532: push.pri
3536: load.s.pri -4
3544: pop.alt
3548: jsless 3592
3556: break
3560: const.pri 2280
3568: push.pri
3572: sysreq.n 2 1
3584: jump 3620
3592: break // 3548
3596: const.pri 2288
3604: push.pri
3608: sysreq.n 2 1
3620: break // 3584
3624: zero.pri
3628: stor.s.pri -4
3636: break
3640: load.s.pri -4
3648: push.pri
3652: const.pri 10
3660: stor.s.pri -4
3668: pop.alt
3672: xchg
3676: sgeq
3680: heap 4
3688: stor.i
3692: move.pri
3696: push.pri
3700: const.pri 2296
3708: push.pri
3712: sysreq.n 2 2
3724: stack 4
3732: heap.restore
3736: break
3740: zero.pri
3744: retn
3748: endproc
```

**Comment by Kailo97** [comment]
Ok, I understand now. Is undefined behavior case. Close if nothing planned
https://en.cppreference.com/w/cpp/language/eval_order
More close case of problem i can imagine
```
void OnPlayerSpawned(int client)
{
	int weapon = GetClientWeapon(client);
	if (weapon != -1)
	{
		DataPack pack;
		CreateDataTimer(10.0, Timer_DelaySpawn, pack);
		pack.WriteCell(GetClientUserId(client));
		pack.WriteCell(EntIndexToEntRef(weapon));
	}
}

public Action Timer_DelaySpawn(Handle timer, DataPack pack)
{
	pack.Reset();
	// expecting that left call "ReadCell" would first
	if (GetClientOfUserId(pack.ReadCell()) == GetWeaponOwner(EntRefToEntIndex(pack.ReadCell())))
	{
		...
	}
}
```

**Comment by dvander** [comment]
Let me think about that case. I'm conflicted because it's an anti pattern, eg put an && or || in there and suddenly the state of "pack" is extremely confusing.But defining eval order as left to right is not very controversial either...On Jun 6, 2023 2:31 PM, Maxim Telezhenko ***@***.***> wrote:
Ok, I understand now. Is undefined behavior case. Close if nothing planned
https://en.cppreference.com/w/cpp/language/eval_order
More close case of problem i can imagine
void OnPlayerSpawned(int client)
{
	int weapon = GetClientWeapon(client);
	if (weapon != -1)
	{
		DataPack pack;
		CreateDataTimer(10.0, Timer_DelaySpawn, pack);
		pack.WriteCell(GetClientUserId(client));
		pack.WriteCell(EntIndexToEntRef(weapon));
	}
}

public Action Timer_DelaySpawn(Handle timer, DataPack pack)
{
	pack.Reset();
	// expecting that left call "ReadCell" would first
	if (GetClientOfUserId(pack.ReadCell()) == GetWeaponOwner(EntRefToEntIndex(pack.ReadCell())))
	{
		...
	}
}

**Comment by dvander** [comment]
Thanks for the great test case. The bug was in CodeGenerator::EmitChainedCompareExprTest, which for some reason evaluates right-to-left. Probably, I knew that the compare opcodes are swapped, and didn't want to swap the operands at runtime. But that's what's needed.

**Comment by dvander** [comment]
Fixed on master.
