### ISSUE TITLE
Chained preprocessor conditions give warning

### ISSUE THREAD

**Issue by Alienmario** [alliedmodders/sourcepawn#889]
After upgrading to SM build 7032, this has started giving warnings, while still functioning as expected.
```sourcepawn
#include <sourcemod>

#define A 1
#define B 1

public void OnPluginStart()
{
    #if defined A && defined B
    PrintToServer("AND OK");
    #endif
    
    #if defined A || defined B
    PrintToServer("OR OK");
    #endif
}
```
test.sp(8) : warning 206: redundant test: constant expression is non-zero
test.sp(8) : warning 206: redundant test: constant expression is non-zero
test.sp(12) : warning 206: redundant test: constant expression is non-zero
test.sp(12) : warning 206: redundant test: constant expression is non-zero

**Comment by dvander** [comment]
Thanks for the test case, this has been fixed on master.
