### ISSUE TITLE
new-style argument type check is missing in includes

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcepawn#896]
1) Case A: no custom include

```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>

stock void foo(arg)
{
}

stock void foo2(arg[3])
{
}
```
Log:
```
...\1.sp(6) : error 147: new-style declarations are required
...\1.sp(10) : error 147: new-style declarations are required
```

2) Case B:

1.sp
```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>
#include <test>

public void OnPluginStart()
{
	foo(1);
}
```

test.inc
```
stock void foo(arg)
{
}

stock void foo2(arg[3])
{
}
```
Log:
```
no errors
no warnings
```

**Comment by asherkin** [comment]
This was an intentional change, pragmas are now file-scoped.

**Comment by sapphonie** [comment]
> This was an intentional change, pragmas are now file-scoped.

Booo

**Comment by dvander** [comment]
I'm thinking of going an alternate route in 1.12: having a warning if there is any old decl, anywhere. New code should never have old decls and porting should be a one-time deal. 1.12 would be the last compiler with old decl support.
