### ISSUE TITLE
`\x0` overridden into `\x`

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [alliedmodders/sourcepawn#909]
`\x` Is used to print out ASCII characters, e.g. `\x23` as `#`, `\x4C` as `L`.
This works fine, however in SM version `1.12.0.7054` it now also works with `\x023`, `\x04C` etc. This is a problem when source games uses `\x01` to `\x08` to display colors, breaking any old plugins that use this method.

For example, `\x04Colors!` would normally show `Colors!` with `\x04` color prefix, but now `\x04C` get replaced into ASCII character `L`, showing `Lolors!` instead without any colors.

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
