### ISSUE TITLE
unknown directive - Sourcepawn 1.12

### ISSUE THREAD

**Issue by theelsaud** [alliedmodders/sourcepawn#913]
Hello!
I'm having problems compiling my plugin on Sourcepawn 1.12

`
VIP-Core/API.sp(47) : error 031: unknown directive
`

On later versions everything worked correctly.

_______________

As I understand it, the work in macros has changed
https://github.com/theelsaud/VIP-Core-Reloaded/blob/main/scripting/VIP-Core/API.sp#L2

Actions with other version Sourcepawn: https://github.com/theelsaud/VIP-Core-Reloaded/actions/runs/6493079027

P.S. Question to dvander, will there be x64 support, and relatively added int64?)

**Comment by dvander** [comment]
SourcePawn works on any platform. A 64-bit integer type is on my todo list, but no ETA.

**Comment by dvander** [comment]
Against my better judgment, this is now fixed on master.
