### ISSUE TITLE
spcomp --warning option does not work

### ISSUE THREAD

**Issue by bakugo** [alliedmodders/sourcepawn#918]
`-w, --warning=WARNING     Disable a specific warning by its number.`

This doesn't seem to work at all, whatever warning I try to disable still appears.

For example, compiling the following plugin with `spcomp test.sp --warning=203`:

```sourcepawn
int test;
public void pub() {}
```

Still shows warning 203:

```
SourcePawn Compiler 1.12
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

test.sp(1) : warning 203: symbol is never used: "test"
     1 | int test;
-------------^
Code size:         28 bytes
Data size:         4 bytes
Stack/heap size:      16448 bytes
Total requirements:   16480 bytes
```

**Comment by dvander** [comment]
Thanks, this has been fixed in master.
