### ISSUE TITLE
Floats with exponents no longer parse?

### ISSUE THREAD

**Issue by rtldg** [alliedmodders/sourcepawn#922]
with the 7080 sm 1.12, this plugin
```cpp
public void OnPluginStart()
{
	float x = 1.2e3;
}
```
does this
```
//// test.sp
//
// .\test.sp(3) : error 425: exponential must be followed by integer
//      3 |     float x = 1.2e3;
// --------------------^
//
// 1 Error.
//
// Compilation Time: 0.3 sec
// ----------------------------------------
```

The errors seems to come from https://github.com/alliedmodders/sourcepawn/blob/d59a51b5741823903ecbe8c014632ee1f8aad65d/compiler/lexer.cpp#L280-L289 

Presumably `ndigits` is supposed to be incremented if `IsDigit()` but I'm making an issue instead of a pull-request because I'm not positive.

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
