### ISSUE TITLE
Compiler warning related to bit operations

### ISSUE THREAD

**Issue by A1mDev** [alliedmodders/sourcepawn#954]
This is due to yesterday's sourcepawn updates, the code stopped working correctly:
![2312009 6300000004_image](https://github.com/alliedmodders/sourcepawn/assets/33463136/c7c1c847-d923-427d-9900-f7d0cc7000f5)

**Comment by accelerator74** [comment]
There are also some more errors
![image](https://github.com/alliedmodders/sourcepawn/assets/18032476/2e82cf2c-5b3f-4f11-9fed-8c2d47e6f6be)
![image](https://github.com/alliedmodders/sourcepawn/assets/18032476/1545adfc-7c19-4a07-87f7-f8fc1ebad9e8)

**Comment by dvander** [comment]
Please attach reproducible test cases.

**Comment by A1mDev** [comment]
This was the code with the `OnPlayerRunCmd`: 
```
public Action OnPlayerRunCmd(int client, int& buttons, int& impulse, float vel[3], float angles[3], int& weapon, int& subtype, int& cmdnum, int& tickcount, int& seed, int mouse[2])
{
	buttons &= ~IN_ATTACK;
	
	return Plugin_Changled;
}
```

I can’t check it now, since I deleted that sourcemod build, but it seems that it can be reproduced using the usual function:
```
void Foo(int &buttons)
{
    buttons &= ~IN_ATTACK;
}
```

**Comment by A1mDev** [comment]
Case 2:
```
void Foo()
{
    float vMins[3];
    float vMaxs[3];
    vMins = view_as<float>({-14.0, -25.0, -12.0});
    vMaxs = view_as<float>({13.0, 25.0, 12.0});
}
```

**Comment by dvander** [comment]
Thanks! These have both been fixed on master.
