### ISSUE TITLE
Sourcepawn extremely slow on x64 without JIT

### ISSUE THREAD

**Issue by bottiger1** [alliedmodders/sourcepawn#965]
Just wanted to bring to attention that porting the JIT to x64 is urgently needed for proper 64 bit support.

I've been running a TF2 server on x64 for the last 2 days without any issues with the fixes I've recently made to sourcemod except for one.

The CPU usage is much higher due to the lack of JIT on x64. I'd estimate it is around 50% higher. The server doesn't have many heavy plugins on it. The biggest plugin being used is smac and the profiler shows that most of the cpu usage is being used on the OnPlayerRunCmd callback.

![prof](https://github.com/alliedmodders/sourcemod/assets/55270538/fa345834-d614-47a5-90a3-f7c8eb162e1f)

Porting the JIT is outside my area of expertise so I am wondering if anyone has any plans for it.

**Comment by dvander** [comment]
Let's see where we are w/ that fix in. If it's still bad, I can take a look to see if there are any easy wins. New JIT isn't a _huge_ ask but there's probably just dumb stuff to fix in the meantime.

**Comment by bottiger1** [comment]
![perf2](https://github.com/alliedmodders/sourcepawn/assets/55270538/6e9b7266-64d7-4478-9834-cc0b89e51c90)

seems better now

**Comment by dvander** [comment]
Great!
