### ISSUE TITLE
Regression: missing error for array "initialization data exceeds declared size"

### ISSUE THREAD

**Issue by peace-maker** [alliedmodders/sourcepawn#971]
Also, the compiler stopped complaining about an overflowed array, like this:
```pawn
char str[10] = "asdasdsadassadadsdas";
```
The compiler on sm 1.10 reported an error:
> error 018: initialization data exceeds declared size

_Originally posted by @accelerator74 in https://github.com/alliedmodders/sourcepawn/issues/970#issuecomment-2149503114_

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
