### ISSUE TITLE
[Feature Request] Debug MetaData support for non-JIT builds

### ISSUE THREAD

**Issue by KaelaSavia** [alliedmodders/sourcepawn#981]
at the moment there is no JIT support for 64-bit and in result no debug metadata ( JITMetadata from core.cfg in sourcemod) 
having some kind of debug metadata on x64 would be quite helpful although I am not sure how viable it is performance wise on non-JIT

**Comment by asherkin** [comment]
What sort of info are you after from it? I don't think any of the standard stuff could work with interpreter stacks, but they should already have relevant info available.

**Comment by dvander** [comment]
Feel free to reopen if more information can be provided.
