### ISSUE TITLE
Enum struct param incorrectly marked as unused

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [alliedmodders/sourcepawn#991]
In `1.12.0.7165`, If function have an enum struct in param that were to be only used to reassign from another enum struct, it would incorrectly be marked as unused, as enum struct/array should be passed as a reference.

Example code, both lines setting `value` variable is unneeded to reproduce this warning, but just to prove that it was in fact still used and that the value number has changed.
```sp
enum struct Foo
{
	int value;
}

public void OnPluginStart()
{
	Foo param;
	param.value = 0;
	FunctionWithStructParam(param);
	PrintToServer("%d", param.value);	// printed "1"
}

void FunctionWithStructParam(Foo param)	// warning 204: symbol is assigned a value that is never used: "param"
{
	Foo bar;
	bar.value = 1;
	param = bar;
}
```

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
