### ISSUE TITLE
Passing |this| into an any[] parameter results in an argument type mismatch

### ISSUE THREAD

**Issue by Bradasparky** [alliedmodders/sourcepawn#993]
Compilers used to test this code are 1.12.0.7165 & 1.13.0.7168. 
```c++
enum struct MyStruct
{
    int i;

    void FuncA()
    {
        FuncB(this); // error 035: argument type mismatch (argument 1)
    }
}

void FuncB(any[] arr) { }
```

*Edit: The error doesn't happen if the parameter of `FuncB` is changed to `const any[] arr`

**Comment by dvander** [comment]
Thanks for the reduced test case, this has been fixed on master.
