### ISSUE TITLE
Creating an array of enum struct have non-initialized values skipped and put into wrong place.

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [alliedmodders/sourcepawn#995]
Normally when creating an array of enum struct but without all values being set, these values would be set to 0 by default. But in latest version it was just skipped, setting value elsewhere instead.

```sp
enum struct Numbers
{
	int first;
	int second;
	int third;
}

static Numbers list[] = {
	{ 1, 2 },
	{ 4, 5, 6 },
	{ 7 },
}

public void OnPluginStart()
{
	for (int i = 0; i < sizeof(list); i++)
		PrintToServer("index %d: %d %d %d", i, list[i].first, list[i].second, list[i].third);
}
```

Latest version gives this result:
```
index 0: 1 2 4
index 1: 5 6 7
index 2: 0 0 0
```

While this is the expected/correct result from SM 1.11:
```
index 0: 1 2 0
index 1: 4 5 6
index 2: 7 0 0
```

**Comment by dvander** [comment]
This test case can be reduced to:

    printnum(list[2].first);

The rest of it is undefined behavior since it reads beyond the end of the array.
