### ISSUE TITLE
Segfault on compile

### ISSUE THREAD

**Issue by OfficerSpy** [alliedmodders/sourcepawn#996]
Compiler 1.12.0.7165 started crashing with code that previously worked before, and I'm not sure why it does now. Build 1.12.0.7169 does not work either.
```
/opt/hostedtoolcache/sourcepawn/1.12.7165/x64/spcomp: line 3:  2208 Segmentation fault      (core dumped)
/opt/hostedtoolcache/sourcepawn/1.12.7165/x64/spcomp64_original -i/opt/hostedtoolcache/sourcepawn/1.12.7165/x64/include $@
```

**Comment by dvander** [comment]
Please re-file or re-open when you have steps to reproduce.
